### ISSUE TITLE
Archive Blob Storage and Blob-Level Tiering

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-storage-blob-go#1]
Ported from https://github.com/Azure/azure-sdk-for-go/issues/808

Is there a timeline for adding support for Archive Blob Storage and Blob-Level Tiering to this SDK?
(or are those expected to come in through public contributions?)

[Announcing the public preview of Azure Archive Blob Storage and Blob-Level Tiering](https://azure.microsoft.com/en-us/blog/announcing-the-public-preview-of-azure-archive-blob-storage-and-blob-level-tiering/)

**Comment by JeffreyRichter** [comment]
This is now supported in our 2017-07-29 package version. See [SetTier](https://github.com/Azure/azure-storage-blob-go/blob/master/2017-07-29/azblob/url_blob.go#L109)
