### ISSUE TITLE
[Feature Request] Cleanup failed UploadBufferToBlockBlob?

### ISSUE THREAD

**Issue by someone1** [Azure/azure-storage-blob-go#101]
Part of this is a "how does Azure's Storage API" work question - what happens if a file is abandoned (for whatever reason) during a block blob upload and never "cleaned up"? Are the blocks counted against the user in terms of storage? If so, how can we "clear" this abandoned upload?

Google's Cloud Storage will auto-expire upload sessions after 1 week. AWS S3 allows you to abort a multipart upload. Additionally, S3 allows you to place lifecycle rules on failed multipart uploads to reclaim the space that is otherwise inaccessible but billed to your account.

Can the high level APIs provided by this SDK handle the appropriate post-error action? I know AWS S3 Go SDK will actually abort a multipart upload if it fails for whatever reason unless an option is passed  in to "keep parts." I think it would be helpful and easily align users to "best practices" if the SDK provided the correct action to take after a block blob upload.

**Comment by JeffreyRichter** [comment]
See https://docs.microsoft.com/en-us/rest/api/storageservices/put-block-list:
Any uncommitted blocks will be garbage collected if there are no successful calls to Put Block or Put Block List on the blob within a week following the last successful Put Block operation. If Put Blob<https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob> is called on the blob, any uncommitted blocks will be garbage collected.


  *   Jeffrey Richter (watch Architecting Distributed Cloud Apps<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fazure.microsoft.com%2Ftraining%2Fdistributed-cloud-apps%2F&data=02%7C01%7Cjeffreyr%40microsoft.com%7C948cf3366acf45f6ef8d08d62e3b3b00%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636747229263047172&sdata=sg%2FtzHWpscWQDr7foOSsaNrKDP5vNSHE3b72HJG8swU%3D&reserved=0>)

**Comment by someone1** [comment]
Great, thanks! I was having trouble navigating azure storage documentation and didn't come across this article.
