### ISSUE TITLE
Website URL 404

### ISSUE THREAD

**Issue by jdanlewis** [Azure/azure-storage-blob-go#102]
### Which version of the SDK was used?
n/a

### Which platform are you using? (ex: Windows, Linux, Debian)
n/a

### What problem was encountered?

Website URL cannot be found by godoc.org's team of gophers.

### How can we reproduce the problem in the simplest way?

1. Go to https://github.com/Azure/azure-storage-blob-go
2. Go to the website URL (https://godoc.org/github.com/Azure/azure-storage-blob-go/2016-05-31/azblob) next to the repository description ("Microsoft Azure Blob Storage Library for Go") 

### Have you found a mitigation/solution?

Replace the URL with https://godoc.org/github.com/Azure/azure-storage-blob-go/azblob

**Comment by zezha-msft** [comment]
Hi @jdanlewis, thanks for reaching out!

We are aware of this problem, and we are trying to find the person with the right permissions to update it. 😄

**Comment by zezha-msft** [comment]
@jdanlewis the bad link is now removed. The GoDoc widget at the top of the README is pointing to the right place.
