### ISSUE TITLE
Releases should be prefixed with a 'v'

### ISSUE THREAD

**Issue by JeremyLoy** [Azure/azure-storage-blob-go#110]
[See the official Go modules documentation here](https://github.com/golang/go/wiki/Modules#modules). Prefixing the tag with a `v` is required.

**Comment by zezha-msft** [comment]
Hi @JeremyLoy, thanks for reaching out!

I'll tag the next release with a 'v'. 👍

**Comment by zezha-msft** [comment]
Hi @JeremyLoy it's fixed in `v0.6.0`. Thank you!
