### ISSUE TITLE
service principal access support

### ISSUE THREAD

**Issue by dagger** [Azure/azure-storage-blob-go#126]
### Which version of the SDK was used?
0.3.0
### Which platform are you using? (ex: Windows, Linux, Debian)
linux
### What problem was encountered?
Cannot use service principal to access blob storage.
### How can we reproduce the problem in the simplest way?
The credentials support is limited to shared key, anonymous, and token based.
### Have you found a mitigation/solution?
no

Is there any plan to support Service Principal support? It will solve a lot of issues, especially cross-project account access.

**Comment by zezha-msft** [comment]
Hi @dagger, thanks for reaching out.

Token based authentication actually includes Service Principle, which is just a way of getting access tokens from AAD. Please refer to this [article](https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad) for more information.

Please also upgrade to the latest version if possible.

**Comment by dagger** [comment]
Thank you!

**Comment by dagger** [comment]
@zezha-msft can you point me to an example of fetching the token from AAD in golang?

**Comment by Virepri** [comment]
@dagger Look at Azure/go-autorest/autorest/adal

**Comment by kwontae** [comment]
I'm having trouble finding a good guide to how I can authorize into Blob storage. @Virepri 
Let me know if i have the flow wrong.
First adal.NewServicePrincipalToken(oauthconfig, spn client id, spn client secret, name of the blob storage(is that what resource string is for?)) -> returns ServicePrincipalToken. 
Secondly, use that servicePrincipalToken as an input to azblob.NewTokenCredential()?

**Comment by adreed-msft** [comment]
Hi, @kwontae!

Yes, you'd use the access token from the OAuth token given, alongside a refresher.

**Comment by kwontae** [comment]
@adreed-msft  Sorry i'm very new to this stuff. Quick question. What is the refreshcallback for? What information do i need to provide for that. I tried looking through test cases, but didn't get much from it

**Comment by adreed-msft** [comment]
The refresh callback does two things:

1) it refreshes the token
2) it returns when next to refresh the token.

Since SPA doesn't return a refresh token, you should just call your login code again.

**Comment by kwontae** [comment]
@adreed-msft oh hmm.
So basically I do 
`spnToken := adal.NewServicePrincipalToken(MyOauthConfig, spn_client_id, spn_client_secret, blob_storage_url)` 
`tokenString := spnToken.OAuthToken()`
`tokenCred := azblob.NewTokenCredential(tokenString, tokenrefresher)`
and the tokenRefresher is just my own struct object that implements a function that returns `time.Duration`?

**Comment by adreed-msft** [comment]
Yup, to both of your questions!

**Comment by adreed-msft** [comment]
and tokenrefresher is actually a function-- functions are first class citizens in Go.

**Comment by kwontae** [comment]
ohh do you mind providing an example of tokenRefresher?

**Comment by kwontae** [comment]
@adreed-msft  
`var tokenRefresher azblob.TokenRefresher`
`tokenRefresher = func(credential azblob.TokenCredential) time.Duration { //call my login function and return some random time.Duration that I want}`
does this look right?

**Comment by ItalyPaleAle** [comment]
I was able to get this to work, thanks to the tips in the comments here. In case it can help someone else too: https://gist.github.com/ItalyPaleAle/ec6498bfa81a96f9ca27a2da6f60a770
