### ISSUE TITLE
Issue with an example

### ISSUE THREAD

**Issue by ycsunil** [Azure/azure-storage-blob-go#128]
### What problem was encountered?
Example posted for configuring pipeline has issue. Compiler complains "return &httpResponse{response: resp}, err" as undefined. Please update doc with return statement "return pipeline.NewHTTPResponse(resp), err"

Link to example: https://godoc.org/github.com/Azure/azure-storage-blob-go/azblob#example-NewPipeline

**Comment by zezha-msft** [comment]
Thanks @ycsunil! I've fixed it [here](https://github.com/Azure/azure-storage-blob-go/commit/f5b36168019d8f300887e93f846dc56020307ef2).
