### ISSUE TITLE
Access with a SAS key rather than account key

### ISSUE THREAD

**Issue by edwardsp** [Azure/azure-storage-blob-go#130]
I would like to be able to create credentials from a SAS key rather than using the account key.  I see the from the docs there is NewAnonymousCredential (https://godoc.org/github.com/Azure/azure-storage-blob-go/azblob#NewAnonymousCredential) but I can see how to use it.  Basically I want to replace this in my code:

    credential, err := azblob.NewSharedKeyCredential(accountName, accountKey)

With a similar call passing the accountName and SAS key.  Is this possible?

Thanks,
Paul

### Which version of the SDK was used?
Latest

### Which platform are you using? (ex: Windows, Linux, Debian)
Linux

### What problem was encountered?
N/A

### How can we reproduce the problem in the simplest way?
N/A

### Have you found a mitigation/solution?
N/A

**Comment by JeffreyRichter** [comment]
A SAS token (not key) is just a set of query parameters that are part of the container or blob's URL. So, just append the SAS token to the URL and use anonymous credentials and you can perform operations on the container or blob.


  *   Jeffrey Richter (watch Architecting Distributed Cloud Apps<https://azure.microsoft.com/training/distributed-cloud-apps/>)

________________________________

**Comment by zezha-msft** [comment]
@edwardsp please let us know if you have any other question.

**Comment by zezha-msft** [comment]
Samples are [here](https://github.com/Azure/azure-storage-blob-go/blob/master/azblob/zt_examples_test.go#L351).
