### ISSUE TITLE
Access using AAD

### ISSUE THREAD

**Issue by sandeepkru** [Azure/azure-storage-blob-go#132]
### Which version of the SDK was used?
Current version 0.6.0

### Which platform are you using? (ex: Windows, Linux, Debian)
Linux

This is more of a question than an issue, I see that there is a way to authenticate azure storage with AAD in this [.Net example](https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-msi). I couldn't find any examples in `go code` to support something like this. Is this supported. Can you please confirm if this is supported? 

We have an active issue [rclone#3213](https://github.com/ncw/rclone/issues/3213), AAD authentication feature with storage would help unblocking this.

**Comment by zezha-msft** [comment]
Hi @sandeepkru, yes, token credential is supported. 

I'll add samples soon. In the mean time, please refer to this [project](https://github.com/Azure/azure-storage-azcopy/blob/master/common/credentialFactory.go#L102).

**Comment by sandeepkru** [comment]
Thank you!

**Comment by kwontae** [comment]
Where is the sample? @zezha-msft
