### ISSUE TITLE
Segfault when UploadFileToBlockBlob return errors

### ISSUE THREAD

**Issue by ramielrowe** [Azure/azure-storage-blob-go#139]
### Which version of the SDK was used?

8a1deeeabe0a24f918d29630ede0da2a1c8f3b2f

### Which platform are you using? (ex: Windows, Linux, Debian)

Linux

### What problem was encountered?

Errors can be returned by [doBatchTransfer](https://github.com/Azure/azure-storage-blob-go/blob/master/azblob/highlevel.go#L298) before all goroutines have finished. There are two compounding reasons for this. First, this [cancel](https://github.com/Azure/azure-storage-blob-go/blob/master/azblob/highlevel.go#L341) doesn't wait for anything to finish before returning. Second, the [context that is cancelled](https://github.com/Azure/azure-storage-blob-go/blob/master/azblob/highlevel.go#L303), isn't actually used by anything. This ends up racing this [Munmap call](https://github.com/Azure/azure-storage-blob-go/blob/master/azblob/highlevel.go#L150), which will unmap the file out from under active goroutines during errors. This ends up causing segfaults.

### How can we reproduce the problem in the simplest way?

Sample golang code to reproduce: https://gist.github.com/ramielrowe/cf41891d38fa9bf636b7f45eb81a0cd0#file-mmap_segfault-go

### Have you found a mitigation/solution?

Here's an example pattern that will safely return errors and run munmap.

https://gist.github.com/ramielrowe/cf41891d38fa9bf636b7f45eb81a0cd0#file-mmap_safe-go

**Comment by zezha-msft** [comment]
Hi @ramielrowe, thanks for reaching out and providing such details repro steps!

I've logged this bug to be investigated/addressed.

**Comment by svrc-pivotal** [comment]
We've been running into these segfaults fairly regularly on 0.7.0.

**Comment by feiyushi** [comment]
We may have hit the same error but in a different method `DownloadBlobToFile`. 
This segfault has caused our containers to restart and thus unnecessarily prolonged the operation execution time and sometimes caused operation failures.
Here's a **unordered** call stack extracted from production log, hope it helps:
```
goroutine 1045 [running]:
panic: runtime error: invalid memory address or nil pointer dereference
u0009/vendor/github.com/Azure/azure-storage-blob-go/azblob/zz_response_helpers.go:62 +0x2dd
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x55c9f5f5e98d]
vendor/github.com/Azure/azure-storage-blob-go/azblob.(*DownloadResponse).Body(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2e, 0xc00029e4b6)
vendor/github.com/Azure/azure-storage-blob-go/azblob.downloadBlobToBuffer.func1(0x0, 0xe000, 0x1, 0x101)
vendor/github.com/Azure/azure-storage-blob-go/azblob.doBatchTransfer.func2(0xc000bdaa20, 0xc0005fffa8)
vendor/github.com/Azure/azure-storage-blob-go/azblob.doBatchTransfer.func1(0xc000bdaa20, 0xc000b51380)
u0009/vendor/github.com/Azure/azure-storage-blob-go/azblob/highlevel.go:329 +0x3d
u0009/vendor/github.com/Azure/azure-storage-blob-go/azblob/highlevel.go:312 +0x41
u0009/vendor/github.com/Azure/azure-storage-blob-go/azblob/highlevel.go:208 +0x142
created by aibrp/vendor/github.com/Azure/azure-storage-blob-go/azblob.doBatchTransfer
u0009/vendor/github.com/Azure/azure-storage-blob-go/azblob/highlevel.go:309 +0x193
```
