### ISSUE TITLE
Progress Indicator in UploadStreamToBlockBlobOptions

### ISSUE THREAD

**Issue by patnaikshekhar** [Azure/azure-storage-blob-go#143]
### Which version of the SDK was used?
Latest

### Which platform are you using? (ex: Windows, Linux, Debian)
Linux Ubuntu 19.04

### What problem was encountered?
Feature Request - I'm trying to upload large files to Blob Storage and the best way to do that is using streams. It would be very useful to show the user a progress indicator. Unfortunately the UploadStreamToBlockBlobOptions does not support a progress callback / function.

### How can we reproduce the problem in the simplest way?
Feature Request

### Have you found a mitigation/solution?
No

**Comment by JeffreyRichter** [comment]
Actually, you can do this now by wrapping the steam with a RequestBodyProgress stream. See https://godoc.org/github.com/Azure/azure-storage-blob-go/azblob#example-package--ProgressUploadDownload for an example.


  *   Jeffrey Richter (watch Architecting Distributed Cloud Apps<https://azure.microsoft.com/training/distributed-cloud-apps/>)

________________________________

**Comment by patnaikshekhar** [comment]
Thanks @JeffreyRichter - is **Upload()** the preferred way to upload streams instead of using UploadStreamToBlockBlob. Some of the other SDKS such as Nodejs (https://docs.microsoft.com/en-us/javascript/api/@azure/storage-blob/iuploadtoblockbloboptions?view=azure-node-preview) allow you to pass a progress callback to **uploadStreamToBlockBlob()**

**Comment by JeffreyRichter** [comment]
For Go, progress is accomplished by wrapping any steam with the progress steam. The Upload
Function uploads a steam to a blob the max side is 250MB (if I remember correctly- PUT BLOB rest API). UploadStreamToBlockBlob will upload a steam that is much larger by breaking it into blocks and uploading each block. Also, Upload Steam to block blob does not require the steam to be seekable and so it can used by network-backed steams. Upload requires that the steam be seekable (like for memory buffers or files).

Upload is more efficient
Node doesn't have streams, so it is done differently.


  *   Jeffrey Richter (watch Architecting Distributed Cloud Apps<https://azure.microsoft.com/training/distributed-cloud-apps/>)

________________________________

**Comment by patnaikshekhar** [comment]
Thanks @JeffreyRichter that works for me!
