### ISSUE TITLE
Error when uploading large files >2GB

### ISSUE THREAD

**Issue by patnaikshekhar** [Azure/azure-storage-blob-go#144]
### Which version of the SDK was used?
Latest

### Which platform are you using? (ex: Windows, Linux, Debian)
Linux (Ubuntu 19.04)

### What problem was encountered?
azblob.UploadStreamToBlockBlob errors out when uploading a large file > 2GB. It works with files >1GB.

The error that I get is:

RESPONSE ERROR (ServiceCode=InvalidBlobOrBlock)
Description=The specified blob or block content is invalid.
RequestId:7fb1f1b0-901e-0014-09c8-4db062000000
Time:2019-08-08T09:07:17.4462082Z, Details: 
   Code: InvalidBlobOrBlock
   PUT [REDACTED]/bigfiles/file2GB.txt?blockid=wmlDrNfbTT1GqB%2BBFzconwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA%3D%3D&comp=block&timeout=61
   Authorization: REDACTED
   Content-Length: [2097152]
   User-Agent: [Azure-Storage/0.7 (go1.12.7; linux)]
   X-Ms-Client-Request-Id: [aa6316e8-a013-40cd-6069-3104fdcfa96e]
   X-Ms-Date: [Thu, 08 Aug 2019 09:07:15 GMT]
   X-Ms-Version: [2018-11-09]
   --------------------------------------------------------------------------------
   RESPONSE Status: 400 The specified blob or block content is invalid.
   Content-Length: [234]
   Content-Type: [application/xml]
   Date: [Thu, 08 Aug 2019 09:07:16 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [InvalidBlobOrBlock]
   X-Ms-Request-Id: [7fb1f1b0-901e-0014-09c8-4db062000000]
   X-Ms-Version: [2018-11-09]

### How can we reproduce the problem in the simplest way?
```go
func uploadHandler(w http.ResponseWriter, r *http.Request) {
	if err := r.ParseMultipartForm(maxUploadSize); err != nil {
		http.Error(w, "FILE_TOO_BIG", http.StatusBadRequest)
		return
	}

	file, handler, err := r.FormFile("file")
	if err != nil {
		http.Error(w, "INVALID_FILE", http.StatusBadRequest)
		return
	}
	defer file.Close()

	err = uploadToStorageBlob(handler.Filename, file, handler.Size)

	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
	}

	http.Redirect(w, r, "/", 302)
}

func uploadToStorageBlob(fileName string, file multipart.File, size int64) error {

	log.Printf("Starting to upload file %s", fileName)

	progress.Store(fileName, 0)

	_, _, _, containerURL, err := getCredentials()
	if err != nil {
		return err
	}

	ctx := context.Background()

	blobURL := containerURL.NewBlockBlobURL(fileName)

	bufferSize := 2 * 1024 * 1024
	maxBuffers := 3

	_, err = azblob.UploadStreamToBlockBlob(
		ctx,
		pipeline.NewRequestBodyProgress(file, func(bytesTransferred int64) {
			percentage := float64(bytesTransferred) / float64(size) * 100
			progress.Store(fileName, int(percentage))
		}),
		blobURL,
		azblob.UploadStreamToBlockBlobOptions{
			BufferSize: bufferSize,
			MaxBuffers: maxBuffers,
		})

	progress.Delete(fileName)

	log.Printf("Completed uploading. Errors are %v", err)

	return err
}
``` 

### Have you found a mitigation/solution?
No

**Comment by zezha-msft** [comment]
Hi @patnaikshekhar, thanks for reaching out!

I tried with a 4GB file but cannot reproduce the behavior you are seeing. Is it possible that another tool is also manipulating the same blob?

**Comment by patnaikshekhar** [comment]
@zezha-msft thanks for looing into this! No there isn't any other code that is manipulating the same blob. I have reduced the code down to the lines pasted above. Would you be able to share the code you used to test with?

**Comment by zezha-msft** [comment]
Hi @patnaikshekhar, here is the [test code](https://gist.github.com/zezha-msft/b772030196e59501a49ab800c9ca928b) I used. 

If possible, please try again with another file, and see if the problem occurs again.

**Comment by feiyushi** [comment]
@zezha-msft, we're also seeing errors with uploading blob for large files (~4G).
Error: Put https://xxxx.blob.core.windows.net/cc/bb?blockid=!Dz4zrcP54RHh04lvfFZWMrQ%(MISSING)%!D(MISSING)&comp=block&timeout=61: EOF
They occur pretty often if not every time. Not sure if it's SDK or storage problem. 
Curious, @patnaikshekhar how did you get the http response info from the SDK? I'd love to log that as well.
Thanks.

**Comment by zezha-msft** [comment]
Hi @feiyushi, your error message looks different though, are you also getting "The specified blob or block content is invalid."?

**Comment by feiyushi** [comment]
Hi @zezha-msft, we don't get full http response in the error. "Put https://xxxx.blob.core.windows.net/cc/bb?blockid=!Dz4zrcP54RHh04lvfFZWMrQ%(MISSING)%!D(MISSING)&comp=block&timeout=61: EOF"  is the only information we get so our hands are tied and we don't know where to start investigating. If you know ways to gather info other than just logging error, please let me know. Thanks.

**Comment by JeffreyRichter** [comment]
Are you using the latest version of the library? I think we missing the MISSING bug.


  *   Jeffrey Richter (watch Architecting Distributed Cloud Apps<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fazure.microsoft.com%2Ftraining%2Fdistributed-cloud-apps%2F&data=02%7C01%7Cjeffreyr%40microsoft.com%7C82df4ff9e5ae46a5095908d7345e957b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637035453166233741&sdata=4GnkpFUKxlZXGXFr6oQo5GB%2FFNIbDXIZDXUij0q4AEE%3D&reserved=0>)

________________________________

**Comment by feiyushi** [comment]
@JeffreyRichter Yes, we are using version 0.8.0.
[[projects]]
  digest = "1:5041865c1d50f6c46e3aa0638741539129d0a48924abdcc850f93c53af5cac36"
  name = "github.com/Azure/azure-storage-blob-go"
  packages = ["azblob"]
  pruneopts = "UT"
  revision = "fc700035fe4a7020f50d49f420b3c088aed57e03"
  version = "v0.8.0"

**Comment by tgruben** [comment]
@zezha-msft getting the same error as above on 0.8.0 
`Code: InvalidBlobOrBlock
   PUT https://xxxxx.blob.core.windows.net/resonate-molecula/data/20191217/part-00000-75aefcf9-6980-4ca4-8779-84712390a103-c000.csv?blockid=4ULUow8lR%2Bt4VwdUsIh7JQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA%3D%3D&comp=block&timeout=61
   Authorization: REDACTED
   Content-Length: [2097152]
   User-Agent: [Azure-Storage/0.7 (go1.13.4; linux)]
   X-Ms-Client-Request-Id: [885c160d-132c-4adc-5a60-a63c416b7146]
   X-Ms-Date: [Tue, 11 Feb 2020 18:24:35 GMT]
   X-Ms-Version: [2018-11-09]`

**Comment by tgruben** [comment]
After a bit of playing, i have a bit of ugly workaround.  It appears to be an issue with the blob's name. The source name,from s3, being **data/20191217/part-00000-75aefcf9-6980-4ca4-8779-84712390a103-c000.csv**. If i change the destination name to be **t0**, I do not receive the InvalidBlobOrBlock errors.  The original s3 source name worked as long as the file was less than 256Mb, which i suppose has something todo with multi-part uploading.  Anyone have any clarification on why that source name would trigger the InvalidBlobOrBlock error?

**Comment by tgruben** [comment]
i have confirmed its the ".csv".  If i replace with "-csv" all is fine

**Comment by rajeevpadinharepattu** [comment]
It seems azure makes problems with **special characters** in the file name 
I got this error when i upload the file with name **dev_tycoai_28092023.iso**
but an upload with name **dev_tycoai28092023.iso** is worked fine...

**Comment by leo-schick** [comment]
I had a file ending on `.abf`. After changing the type to `.abf-h`, it worked for me. I guess there is an issue with that the upload defines a specific content type based on the file ending to increates the upload speed but then fails whatever reason....

I guess a good way to investigate this would be to specify the mime type when uploading the file if that is possible. I used Azure Storage Explorer and there is no such option.
