### ISSUE TITLE
incorrect shared key signing

### ISSUE THREAD

**Issue by kahing** [Azure/azure-storage-blob-go#146]
The `stringToSign` construction for query param assumes that everything is lower case: https://github.com/Azure/azure-storage-blob-go/blob/master/azblob/zc_credential_shared_key.go#L191

It's not clear if that azure-storage-blob-go can generate query param that contains upper case, but the signing generates incorrect signature when I am trying to use it for datalake gen 2.

**Comment by zezha-msft** [comment]
Hi @kahing, thanks for reaching out!

We'll try to repro this issue and get back to you shortly.

**Comment by zezha-msft** [comment]
Hi @kahing, thanks for your patience.

I was able to generate a valid SAS with the following code:
```go
	containerName := "testc"
	credential, err := azblob.NewSharedKeyCredential("zedevwithnamespace", "REDACTED")
	if err != nil {
		log.Fatal(err)
	}

	SAS, err := azblob.BlobSASSignatureValues{
		Protocol:      azblob.SASProtocolHTTPS,
		ExpiryTime:    time.Now().UTC().Add(48 * time.Hour), // 48-hours before expiration
		ContainerName: containerName,
		Permissions:   azblob.ContainerSASPermissions{Read: true, Write:true, Create:true, Add: true, Delete:true, List:true}.String(),
	}.NewSASQueryParameters(credential)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(SAS.Encode())
```

Please note that the URL should be pointing to the DFS endpoint. For example, the full URL to my container is  `https://zedevwithnamespace.dfs.core.windows.net/testc?[SAS]`.

I used [AzCopy](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10) to validate that I can upload to the DFS endpoint.

Please let me know if you have any other question or concern.

**Comment by kahing** [comment]
Yes, for azure blob this happens to be correct, but my understanding is that the query params are supposed to be signed as lower case. The current code breaks when we try to use it for datalake gen 2 (because datalake gen2's go sdk generates query param that's camel cased)

**Comment by zezha-msft** [comment]
@kahing oh sorry I misunderstood the issue (😭 I saw query params and assumed it was about SAS).

We do not support ADLS Gen2 with this SDK (yet). Very soon, the ADLS Gen2 APIs will be merged into the blob endpoint (they will conform to the same standard as Blob APIs).

In the mean time, if you simply need to upload data to the DFS endpoint, my recommendation would be to use AzCopy which has this support built in. 

If you need to manage directories and whatnot, I recommend using [Storage Explorer](https://azure.microsoft.com/en-us/features/storage-explorer/).

If you have other reasons why you need to interact with the DFS endpoint directly, we do have an internal SDK for ADLS Gen2 [here](https://github.com/Azure/azure-storage-azcopy/tree/master/azbfs). And the signing problem was fixed [here](https://github.com/Azure/azure-storage-azcopy/blob/master/azbfs/zc_credential_shared_key.go#L175). However, we only implemented and tested the APIs that we needed, so it's by no means a complete solution.

**Comment by kahing** [comment]
I currently hijacked your signer to use it in go-autorest: https://github.com/kahing/goofys/blob/master/api/common/conf_azure.go#L67 which is how I came across this problem.

My current workaround is embedding part of the azure-sdk-for-go and fixing this to always use lowercase: https://github.com/kahing/goofys/blob/master/internal/backend_adlv2.go#L1587 . I have to do the embedding anyway because azure-sdk-for-go is unusable out of the box with adls gen 2 because of other bugs so this isn't a big deal. You guys need to consolidate your SDKs :-/

**Comment by zezha-msft** [comment]
@kahing thanks a lot for the feedbacks! I totally agree with you. 👍 

We'll provide official support for ADLS Gen2 with the Blob SDK in the near future.
