### ISSUE TITLE
The HTTP response is not returned when an error occurs

### ISSUE THREAD

**Issue by giventocode** [Azure/azure-storage-blob-go#15]
When an error occurs in the low-level APIs/operations the wrappers of the HTTP responses are not returned. This behavior makes the implementation of scenarios that benefit from knowing the status of the response cumbersome, e.g. identify a 404 to handle when a container does not exist. 

Any thoughts?

**Comment by JeffreyRichter** [comment]
If you can type assert the error to azblob.StorageError then it's ResponseError embedded field has a Response() method on it that returns the *http.Response

**Comment by giventocode** [comment]
Awesome, that works. Thank you!
