### ISSUE TITLE
BlobTrigger - Error indexing, Storage not configured

### ISSUE THREAD

**Issue by HoLue** [Azure/azure-storage-blob-go#150]
Sorry, I am a newbie, so maybe my question is at a wrong place - perhaps you can help me to ask at the right place...

### Which platform are you using? (ex: Windows, Linux, Debian)
Windows, VS Code, Deployment to Azure

### What problem was encountered?
I set up a serverless function with a blob trigger using VS Code. Locally everything worked fine. After deploying to AzureI got the following error message:
```
Error:

Fehler bei Funktion (TestFuncBlobTr/BTFuncTest): Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.BTFuncTest'. Microsoft.Azure.WebJobs.Extensions.Storage: Storage account 'testfuncblobtr' is not configured.

Session Id: c22c3cabcc164b7ebdcc103763cf14bc

Timestamp: 2019-10-17T12:35:13.663Z
```
I have a storage testfuncblobtr, I created the containers I need an the storage is given in the function.json
```
{
  "scriptFile": "__init__.py",
  "bindings": [
    {
      "name": "blobin",
      "type": "blobTrigger",
      "direction": "in",
      "path": "samples-workitems/{blobname}.{blobextension}",
      "connection": "testfuncblobtr"
    },
    {
      "name": "blobout",
      "type": "blob",
      "direction": "out",
      "path": "output/{blobname}_opencv.jpg",
      "connection": "testfuncblobtr"
    }
  ]
}
```
![AzureFunc](https://user-images.githubusercontent.com/55573836/67009724-8c66b480-f0ec-11e9-9163-afd3b0fef259.jpg)
![AzureStorage](https://user-images.githubusercontent.com/55573836/67009734-9092d200-f0ec-11e9-86ae-c1fb10f270cd.jpg)

### How can we reproduce the problem in the simplest way?
VS Code, new function with blob trigger, run local (F5), deploy

### Have you found a mitigation/solution?
No

I googled around for hours without any idea how to fix this problem. So any help is appreciated! Please help!

**Comment by zezha-msft** [comment]
Hi @HoLue, from the error message it looks like it's related to the configuration of the Function, not to the SDK. Please reach out to Azure Support accordingly.
