### ISSUE TITLE
Can you provider some sample code of StageBlockFromURL

### ISSUE THREAD

**Issue by howie** [Azure/azure-storage-blob-go#151]
### Which version of the SDK was used?
v0.6.0
### Which platform are you using? (ex: Windows, Linux, Debian)
Linux/Mac

I want to use [Put Block From URL](https://docs.microsoft.com/en-us/rest/api/storageservices/put-block-from-url) API, which provide server site pull file from url (for better performance)

I read the document and know that StageBlockFromURL implements Put Block From URL API.
I also try to learn from your test case and source code of [azcopy](https://github.com/Azure/azure-storage-azcopy/blob/0eab945c55148746047c75ce9852f9adf39db4c1/ste/sender-blockBlobFromURL.go#L125) , but it still hard to understand
Can you provider some sample code of StageBlockFromURL?

**Comment by zezha-msft** [comment]
Hi @howie, thanks for reaching out!

Maybe the[ test case](https://github.com/Azure/azure-storage-blob-go/blob/master/azblob/zt_url_block_blob_test.go#L73) of the SDK is a better sample. Please let us know if you have any question.
