### ISSUE TITLE
blob azure storage doesn't work in v0.7.0 and v0.8.0

### ISSUE THREAD

**Issue by spacycoder** [Azure/azure-storage-blob-go#154]
### Which version of the SDK was used?
v0.7.0 and v0.8.0

### Which platform are you using? (ex: Windows, Linux, Debian)
Windows

### What problem was encountered?
When doing any type of operation on azure blob storage like listing all blobs i get the following error:

    2019/11/22 09:29:18 -> github.com/Azure/azure-pipeline-go/pipeline.NewError, C:/Users/<username>/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/    error.go:154
    HTTP request failed

    Get https://<accountName>.blob.core.windows.net/asdf?comp=list&restype=container&timeout=61: proxyconnect tcp: dial tcp 10.64.2.21:0: connectex: The requested address     is not valid in its context.
    exit status 1

### How can we reproduce the problem in the simplest way?
The example under works fine in v0.6.0 but fails in v0.7.0 and v0.8.0
```
package main

import (
	"context"
	"fmt"
	"log"
	"net/url"

	"github.com/Azure/azure-storage-blob-go/azblob"
)

func main() {
	accountName := ""
	accountKey := ""

	credential, err := azblob.NewSharedKeyCredential(accountName, accountKey)
	if err != nil {
		log.Fatal(err)
	}

	p := azblob.NewPipeline(credential, azblob.PipelineOptions{})

	u, _ := url.Parse(fmt.Sprintf("https://%s.blob.core.windows.net", accountName))

	serviceURL := azblob.NewServiceURL(*u, p)
	containerURL := serviceURL.NewContainerURL("asdf")

	for marker := (azblob.Marker{}); marker.NotDone(); {
		listBlob, err := containerURL.ListBlobsFlatSegment(context.Background(), marker, azblob.ListBlobsSegmentOptions{})
		if err != nil {
			log.Fatal(err)
		}
		marker = listBlob.NextMarker

		for _, blobInfo := range listBlob.Segment.BlobItems {
			fmt.Print("Blob name: " + blobInfo.Name + "\n")
		}
	}
}

```

### Have you found a mitigation/solution?
It works when i connect my laptop to mobile hotspot. So it probably has something to do with our corporate network. But it also works fine on the corporate network when using v0.6.0. So something must have changed between v0.6.0 and 0.7.0 causing this issue.

**Comment by zezha-msft** [comment]
Hi @spacycoder, thanks for reaching out!

Is it possible that your corp net settings changed from when you last used v0.6? As you can see from the [release log](https://github.com/Azure/azure-storage-blob-go/releases) there hasn't been any change in that respect.

**Comment by spacycoder** [comment]
No it works fine in v0.6.0. 
We don't depend directly on azure-storage-blob-go because we use https://github.com/google/go-cloud/ but their latest update v.0.18.0 gives the same error as above. v0.18.0 has the following upgrades to azure libs: 

github.com/Azure/azure-pipeline-go v0.1.9 -> v0.2.1
github.com/Azure/azure-storage-blob-go v0.6.0 -> v0.8.0



We have tested both gocloud and azure-storage-blob-go on the latest releases and both fails. 
gocloud v0.17.0 works fine and using azure-storage-blob-go v0.6.0 directly also works.

So something has changed in the lateste releases of either azure-pipeline-go or azure-storage-blob-go causing this problem. 

I have also reported this problem to gocloud: https://github.com/google/go-cloud/issues/2708

**Comment by zezha-msft** [comment]
Hi @spacycoder, to confirm, you used the exact same version of Golang as well, right? And both tests (V0.6 and V0.7) were in the same time frame?

**Comment by spacycoder** [comment]
I'm using Go version: 1.13.1 windows/amd64

v0.6.0 works. But v0.7.0 and v0.8.0 doesn't work. 
All versions have been tested at the same time.

**Comment by zezha-msft** [comment]
Hi @spacycoder, it looks to me like the behavior change might be due to[ this update](https://github.com/Azure/azure-pipeline-go/releases/tag/v0.2.0) from the pipeline package, where the [ieproxy](https://github.com/mattn/go-ieproxy) package was adopted, to automatically detect proxies on Windows.

Could you please double check the proxy settings in your environment?
