### ISSUE TITLE
400 Invalid URL on all requests

### ISSUE THREAD

**Issue by ChrisMcKenzie** [Azure/azure-storage-blob-go#158]
### Which version of the SDK was used?
2018-11-09

### Which platform are you using? (ex: Windows, Linux, Debian)
Linux

### What problem was encountered?
In Azure China Cloud.

Using Shared Key Auth All requests receive an HTTP 400 code with and HTML response stating that there is an invalid URL. The issues is that if I take the same url that was printed in the log and use it in Curl it works. 

### How can we reproduce the problem in the simplest way?
use library to attempt any action in azure China.

### Have you found a mitigation/solution?
No this is currently not mitigated and is blocking a production release.

**Comment by adreed-msft** [comment]
Could you give us the entire error output that you get when attempting to use the library?

**Comment by adreed-msft** [comment]
Bonus points, if you could get a fiddler trace of trying to get the properties of a blob, that'd be amazing. Do not include auth in the fiddler trace-- try to get the properties of a public blob or something of that nature instead.

**Comment by ChrisMcKenzie** [comment]
Here is the debug response from the lib, I will certainly work on getting a fiddler trace.

```
===== RESPONSE ERROR (ServiceCode=) =====
Description=failed to unmarshal response body
, Details: (none)
   PUT https://<storage_account>.blob.core.chinacloudapi.cn/<container>/<blob>
   Authorization: REDACTED
   Content-Length: [4194304]
   User-Agent: [Azure-Storage/0.7 (go1.10.3; linux)]
   X-Ms-Client-Request-Id: [b5d3db38-7419-405e-52d3-ca1c441e8171]
   X-Ms-Date: [Mon, 27 Jan 2020 18:13:17 GMT]
   X-Ms-Version: [2018-11-09]
   --------------------------------------------------------------------------------
   RESPONSE Status: 400 Bad Request
   Content-Length: [324]
   Content-Type: [text/html; charset=us-ascii]
   Date: [Mon, 27 Jan 2020 18:13:16 GMT]
   Server: [Microsoft-HTTPAPI/2.0]
xml: (*azblob.storageError).UnmarshalXML did not consume entire <HTML> element

```

**Comment by ChrisMcKenzie** [comment]
I think the biggest issue here is that it is failing to parse the error so I tweaked on the lib to print the raw bytes on failure to parse. this is the raw response from the api
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request - Invalid URL</h2>
<hr><p>HTTP Error 400. The request URL is invalid.</p>
</BODY></HTML>
```

**Comment by ChrisMcKenzie** [comment]
on second though I am not sure I will be able to get fiddler to work in the environment this is running in.

**Comment by adreed-msft** [comment]
> on second thought I am not sure I will be able to get fiddler to work in the environment this is running in.

That's perfectly fine.

So, my couple of stabs in the dark right now are:
- You have invalid characters somewhere in your URL. Make sure there's nothing that needs to be encoded.
or
- CURL is manipulating the URL itself somehow.

**Comment by ChrisMcKenzie** [comment]
hrmm ok. let me take a deeper look. the other interesting bit is we use this same code in the Normal Azure cloud and it works fine. it seems to just be an issue in China

**Comment by ChrisMcKenzie** [comment]
just a quick update, I cannot see anything invalid in the URL.

**Comment by ChrisMcKenzie** [comment]
I don't believe so and I am able to make the same request via cURL on the same box.

**Comment by ChrisMcKenzie** [comment]
Is it possible that the China Blob API is on a different (incompatible) version?

**Comment by zezha-msft** [comment]
@ChrisMcKenzie that's a great guess, it's unlikely that the China Blob is supporting `Ms-Version: [2018-11-09]`. 

The HTML error message is unexpected though. We really apologize for the poor debuggability. Usually it should be a XML error message. This behavior is different from the public could.

One workaround to try is to use a similar policy like this [one](https://github.com/Azure/azure-storage-azcopy/blob/master/ste/mgr-JobPartMgr.go#L66), to simply override the service version to a specific older version, maybe ` 2017-11-09` or `2017-07-29`.

**Comment by ChrisMcKenzie** [comment]
I will try that then

**Comment by adreed-msft** [comment]
> One workaround to try is to use a similar policy like this [one](https://github.com/Azure/azure-storage-azcopy/blob/master/ste/mgr-JobPartMgr.go#L66), to simply override the service version to a specific older version, maybe ` 2017-11-09` or `2017-07-29`.

Perhaps we should consider building something like this into the Go SDK. IIRC, Azure Stack uses a prior service revision as well?

**Comment by zezha-msft** [comment]
@adreed-msft the challenge is that there are many possibilities with the value, and we can't test with all of them nor make any guarantee that the same implementation (using the latest service version) would work.

**Comment by ChrisMcKenzie** [comment]
@zezha-msft and @adreed-msft it appears that if I set the version in the pipeline it gets overwritten by the library. https://github.com/Azure/azure-storage-blob-go/blob/3efca72bd11c050222deab57e25ea90df03b9692/azblob/zz_generated_container.go#L86

**Comment by zezha-msft** [comment]
@ChrisMcKenzie the pipeline should actually overwrite the request preparer, as the pipeline executes last.
