### ISSUE TITLE
azblob.UploadStreamToBlockBlob has bad default options that cause call to never return

### ISSUE THREAD

**Issue by element-of-surprise** [Azure/azure-storage-blob-go#163]
NOTE: After reading this, you might want to just skip down to the bottom.  I re-wrote this code twice in two comments:  made it easier to read, more stable and stripped 85 lines out.

https://github.com/Azure/azure-storage-blob-go/blob/762620a866bab229a9e7aff8c44875c862cab322/azblob/highlevel.go#L470

The main issue is that the code is relying on an UploadStreamToBlockBlobOptions{}, which has bad default values.

In this particular instance:

```go
incoming := make(chan []byte, o.MaxBuffers) 
```

is equivalent to:

```go
incoming := make(chan []byte, 0)
```

So when this line is called:
```go
incoming <- make([]byte, o.BufferSize)
```
The code will block.  incoming isn't being read from yet (that doesn't start until the bottom of the goroutine that hasn't started) and there is no buffer.  So it will never be read from.

The easiest way is to fix this is:

```go
func (u *UploadStreamToBlockBlobOptions) defaults() {
  if u.MaxBuffers == 0 {
    u.MaxBuffers = 1
  }
  ....
}
```

and just call defaults() after you receive the options.

However, my quick look through these code blocks makes me think this is really fragile code that minor optional tweaks can break badly and won't get caught in tests.  Especially with Options that have to be read into other options (as in this case, UploadStreamToBlockBlobOptions is read into UploadStreamOptions). Might be worth a re-write.

**Comment by element-of-surprise** [comment]
Additional info:

This code seems to be flaky too.  Doesn't happen often, but I get this occasionally(maybe this is fixed in head, 0.7.  This is from 0.6:

```
github.com/Azure/azure-storage-blob-go/azblob.newStorageError, github.com/Azure/azure-storage-blob-go/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=InvalidBlockList) =====
Description=The specified block list is invalid.
RequestId:140c932f-301e-00ad-24c9-f775ab000000
Time:2020-03-11T17:24:05.0559587Z, Details: 
   Code: InvalidBlockList
   PUT <redacted>
   Content-Length: [14198]
   Content-Type: [application/xml]
   User-Agent: [Azure-Storage/0.6 (go1.13; linux)]
   X-Ms-Blob-Cache-Control: []
   X-Ms-Blob-Content-Disposition: []
   X-Ms-Blob-Content-Encoding: []
   X-Ms-Blob-Content-Language: []
   X-Ms-Blob-Content-Type: []
   X-Ms-Client-Request-Id: [85ccda77-83d9-4e52-7929-3c04ea7c3864]
   X-Ms-Version: [2018-11-09]
   --------------------------------------------------------------------------------
   RESPONSE Status: 400 The specified block list is invalid.
   Content-Length: [221]
   Content-Type: [application/xml]
   Date: [Wed, 11 Mar 2020 17:24:04 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [InvalidBlockList]
   X-Ms-Request-Id: [140c932f-301e-00ad-24c9-f775ab000000]
   X-Ms-Version: [2018-11-09]
```

**Comment by element-of-surprise** [comment]
I had a little extra time today, so I re-wrote this block of code to avoid these problems in the future.

This version is not an ideal Go version, but the structure has limitations. 

This one would work with MaxBuffers == 0.  

This should still have defaults() because you have to ask what would happen with things like negative values.  Also, we need to have sane values for BufferSize.  You could replace with a .validate() that gets checked that these values are within limits we want and if not returns an error.

I removed the whole incoming channel code.   That is trying to make a circular buffer pool.  This was a bad methodology.  I replaced it with a sync.Pool, which is designed for this purpose.

I removed the cancel() and stuff around the Context.  It wasn't required and now we only have to pay attention to the passed context's cancel. This was missing within here (I think it was relying on the t.chunk() error).

That firstErr isn't needed, so it has been removed.

We are still bounded by MaxBuffers (I used it as a channel size).  This shouldn't really be required.  It is unlikely that a value other than 1 will make any difference in benchmarks. It is just wasting memory for the caller because this is all about the writers speed. Reading more in and having back pressure on the writer doesn't do anything.

I've ran this code, which works great within my code so far.  I have not tripped the "Response Error" from above yet or my log.Println() below, yet.

```go
type UploadStreamOptions struct {
	MaxBuffers int
	BufferSize int
}

func (u *UploadStreamOptions) defaults() {
	if u.MaxBuffers < 0 {
		u.MaxBuffers = 1
	}

	if u.BufferSize < 1024 {
		u.BufferSize = 1024
	}
}

type chunk struct {
	num  uint32
	data []byte
}

func (c *chunk) reset(n int) {
	c.num = uint32(n)
}

func uploadStream(ctx context.Context, reader io.Reader, o UploadStreamOptions, t iTransfer) (interface{}, error) {
	o.defaults()

	var bufferPool = sync.Pool{
		New: func() interface{} {
			return chunk{
				data: make([]byte, o.BufferSize),
			}
		},
	}

	toChunk := make(chan chunk, o.MaxBuffers)
	chunkErr := make(chan error, 1)
	if result, err := t.start(ctx); err != nil {
		return result, err
	}

	// Writes out our chunked data.
	wg := sync.WaitGroup{}
	wg.Add(1)
	go func() {
		defer wg.Done()
		for chunk := range toChunk {
			// Note: This looks like something that should be re-written to accept a stream and it should keep track of the chunk count.
			err := t.chunk(ctx, chunk.num, chunk.data)
			bufferPool.Put(chunk)

			if nil != err {
				chunkErr <- err
				return
			}
		}
	}()

	for count := 0; true; count++ {
		chunk := bufferPool.Get().(chunk)
		chunk.reset(count)

		n, err := reader.Read(chunk.data)
		if err != nil && err != io.EOF {
			return nil, err
		}

		if n == 0 {
			// This should really need to be here. But I am suspecting that the chunk numbers being wrong was due to this.
			if err != io.EOF {
				log.Println("bug: reader did not have io.EOF but read 0 bytes")
				count-- // Keeps the count in sync, since we are not sending anything.
				continue
			}
			break
		}

		chunk.data = chunk.data[:n]
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case err = <-chunkErr:
			return nil, err
		case toChunk <- chunk:
			// Do nothing.
		}

		if err == io.EOF {
			break
		}
	}
	close(toChunk)

	wg.Wait()

	// Make sure that we didn't have any errors at the end.
	select {
	case err := <-chunkErr:
		return nil, err
	default:
	}
	return t.end(ctx)
}
```

**Comment by element-of-surprise** [comment]
Ok, so I couldn't leave good enough alone.  The whole iTransfer thing was bothering me and even using goroutines here seemed like overkill.  So I went back and had a look at it. 

iTransfer is an unused abstraction.  It looks like it was designed to be used in multiple places, but didn't end up doing so.  It is only used here to hide: uploadStreamToBlockBlobOptions

So I got rid of iTransfer.  

uploadStreamToBlockBlobOptions has start(), but it didn't do anything but return nil.
So I looked hard at this.

What I found is the code is simply trying to:

- Take an io.Reader
- Read from it and write it to the server in chunks, each chunk gets an id
- Tell the server to commit the chunks that were uploaded

Normally in Go, you want to just use io.Copy() (or one of its other sisters) to copy from a Reader to a Writer.  

So I re-wrote the code to do that, turning uploadStreamToBlockBlobOptions into chunkWriter that implements the io.WriteCloser interface.  

This allows us to drop use of the whole atomicMorphUint32() stuff.  We no longer need synchronization, because writing is serial.  

This code differs from the original in several ways:

- There is no longer an optimization for a single blob push if the data is smaller than the buffer
- MaxBuffers no longer is relevant
- Much easier to look at and debug

The optimization might be a sore spot, but it just doesn't provide enough optimization to pay for its complexity.

This code replaces from current file's line 363 to the bottom of the file.  It shaves off about 85 lines of code.

```go
func UploadStreamToBlockBlob(ctx context.Context, reader io.Reader, blockBlobURL BlockBlobURL,
	o UploadStreamToBlockBlobOptions) (CommonResponse, error) {
	o.defaults()

	result, err := uploadStream(ctx, reader,
		UploadStreamOptions{BufferSize: o.BufferSize, MaxBuffers: o.MaxBuffers},
		newChunkWriter(ctx, blockBlobURL, newUUID(), o),
	)
	if err != nil {
		return nil, err
	}
	return result, nil
}

type chunkWriter struct {
	b             BlockBlobURL
	o             UploadStreamToBlockBlobOptions
	blockIDPrefix uuid // UUID used with all blockIDs

	ctx context.Context

	// nextChunkNum keeps track on which chunk we are on.
	nextChunkNum int

	result *BlockBlobCommitBlockListResponse
}

// newChunkWriter is the constructor for chunkStream.
// Note: Normally it is a faux pas to pass a Context and attach it to a object. However, in certain circumstances
// such as short lived single use object, especially ones that are going to implement an interface, it is okay.
// This Context is used to cause Write() and Close() to error.
func newChunkWriter(ctx context.Context, blockBlobURL BlockBlobURL, blockIDPrefix uuid, o UploadStreamToBlockBlobOptions) *chunkWriter {
	return &chunkWriter{ctx: ctx, b: blockBlobURL, blockIDPrefix: blockIDPrefix, o: o}
}

// Write implements io.Writer.
func (c *chunkWriter) Write(p []byte) (int, error) {
	if c.ctx.Err() != nil {
		return 0, c.ctx.Err()
	}

	blockID := newUuidBlockID(c.blockIDPrefix).WithBlockNumber(uint32(c.nextChunkNum)).ToBase64()
	_, err := c.b.StageBlock(c.ctx, blockID, bytes.NewReader(p), LeaseAccessConditions{}, nil)
	if err != nil {
		return 0, err
	}

	c.nextChunkNum++
	return len(p), nil
}

// Close closes the writer and commits all the blocks.
func (c *chunkWriter) Close() error {
	if c.ctx.Err() != nil {
		return c.ctx.Err()
	}

	blockID := newUuidBlockID(c.blockIDPrefix)
	blockIDs := make([]string, 0, c.nextChunkNum-1)
	for i := 0; i < c.nextChunkNum; i++ {
		blockIDs = append(blockIDs, blockID.WithBlockNumber(uint32(i)).ToBase64())
	}

	var err error
	c.result, err = c.b.CommitBlockList(c.ctx, blockIDs, c.o.BlobHTTPHeaders, c.o.Metadata, c.o.AccessConditions)
	return err
}

type UploadStreamOptions struct {
	MaxBuffers int
	BufferSize int
}

func (u *UploadStreamOptions) defaults() {
	if u.MaxBuffers < 0 {
		u.MaxBuffers = 1
	}

	if u.BufferSize < 1024 {
		u.BufferSize = 1024
	}
}

func uploadStream(ctx context.Context, reader io.Reader, o UploadStreamOptions, writer *chunkWriter) (CommonResponse, error) {
	o.defaults()

	_, err := io.CopyBuffer(writer, reader, make([]byte, o.BufferSize))
	if err != nil {
		return nil, err
	}
	if err := writer.Close(); err != nil {
		return nil, err
	}
	return writer.result, nil
}
```

**Comment by element-of-surprise** [comment]
Next note:

Once I removed the one call to AtomicMorphWhateverItWas, I decided to look at atomicmorph.go .

These were strange and probably could be factored out.  

And indeed, of all the ones defined, only that one was used.  The others were all cruft.  So I removed that file and it built just fine.  There were no associated tests.

**Comment by JeffreyRichter** [comment]
The atomicMorph functions modify a value in a goroutine-safe way. If you remove this, then you opening the code up to race conditions and data corruption. 

The reason why there no associated tests is because you can't test timing. There could be tests for simple scenarios but these are trivial and there is no way to test that it works correctly if 2 or more goroutines attempt to call the function at the exact same moment in time.

**Comment by element-of-surprise** [comment]
I'm aware of what it was being used for.  But, due to the changes to the code, there are no goroutines any longer or channels.  With no concurrency issues, there was is no need for synchronization.

That was the only use of atomicMorph within the package.  The other functions weren't used at all.  So that file could be stripped.

**Comment by JeffreyRichter** [comment]
I see. But without any concurrency, the performance of the upload will suffer. The original design (which may have changed after I worked on this) was to improve perf if reading was faster then writing which is commonly true if reading from a local file and writing to a blob. The design allowed multiple blocks to be uploaded in parallel.

**Comment by element-of-surprise** [comment]
I don't think that is going to be the case with the changes I've made.  I am working directly with the storage maintainers and we are going to benchmark the changes before submission.  If performance suffers, I will make adjustments.

As another note:  A direct test for timing would be difficult, but Go has you covered.  A tight loop test with the race detector turned on would validate that lock specific code works.  While you could just depend on this for the whole test suite, would probably have a specific test for lock specific code.


You can depend on the race detector across the whole code, but if you are introducing speci

**Comment by JeffreyRichter** [comment]
Yes, the race detector might catch this but then that should be run on the actual app not as unit tests on the AtomicMorph functions to make sure that the detector finds a race on the actual value in the app; not some test variable.

**Comment by element-of-surprise** [comment]
As was stated above, you can choose to do that.   It would be my preference to write a small test that worked on a tight loop to detect the issue on a custom sync method.  It is more likely to catch an issue because of the way the race detector works (it does not always catch a race in every run, lots of factors).

However, at this point it is neither here nor there on this bug.  The statement about the tests was simply to inform that there were no tests to remove when I removed the atomicmorph.go file.
