### ISSUE TITLE
BlockBlobURL.CommitBlockList error code?

### ISSUE THREAD

**Issue by sanderdekoning** [Azure/azure-storage-blob-go#164]
When I call `resp, err := BlockBlobURL.CommitBlockList(......)` with an invalid block list, the error variable gets set as expected. However, this err is just the http response object.

This is not very helpful, because `resp` is a nil pointer when an error is returned. This is strange since `resp` is of type `*BlockBlobCommitBlockListResponse` which has an `ErrorCode()` function which in this case should return `InvalidBlockList`, and this is the behaviour that I want.

How can I get the error code from a `resp, err := BlockBlobURL.CommitBlockList(......) ` call?

```
===== RESPONSE ERROR (ServiceCode=InvalidBlockList) =====
Description=The specified block list is invalid.
RequestId:82724516-501e-00a4-30b1-f8fb57000000
Time:2020-03-12T20:59:02.5159931Z, Details: 
   Code: InvalidBlockList
   PUT ......./bpla54856bg0uticgme0?comp=blocklist&timeout=61
   Authorization: REDACTED
   Content-Length: [134]
   Content-Type: [application/xml]
   User-Agent: [Azure-Storage/0.7 (go1.14; linux)]
   X-Ms-Blob-Cache-Control: []
   ......
   X-Ms-Version: [2018-11-09]
   --------------------------------------------------------------------------------
   RESPONSE Status: 400 The specified block list is invalid.
   Content-Length: [221]
   Content-Type: [application/xml]
   Date: [Thu, 12 Mar 2020 20:59:01 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [InvalidBlockList]
   X-Ms-Request-Id: [82724516-501e-00a4-30b1-f8fb57000000]
   X-Ms-Version: [2018-11-09]
```

### Which version of the SDK was used?
`go get github.com/Azure/azure-storage-blob-go/azblob`

### Which platform are you using? (ex: Windows, Linux, Debian)
MacOS 10.15

**Comment by zezha-msft** [comment]
Hi @sanderdekoning, thanks for reaching out.

Please refer to our [sample on error handling](https://github.com/Azure/azure-storage-blob-go/blob/master/azblob/zt_examples_test.go#L221).

**Comment by sanderdekoning** [comment]
Thank you @zezha-msft, that helps me out a lot. I appreciate your time.
