### ISSUE TITLE
timeout=1: context deadline exceeded

### ISSUE THREAD

**Issue by zhangtiedong0912** [Azure/azure-storage-blob-go#165]
### Which version of the SDK was used?
v0.8.0
### Which platform are you using? (ex: Windows, Linux, Debian)
mac
### What problem was encountered?
Trying a simple example to download a file. the file is 4G, I set the timeout of one hour, I can download successfully in my local place, but after the code arrives on the server, it will report an error in less than one minute, as if the timeout I set did not work.
### How can we reproduce the problem in the simplest way?
`
    URL, err := url.Parse("URI_SAS")
	if err != nil {
		logging.Error(logTag, "url parse error: %v", err)
		return err
	}
	p := azblob.NewPipeline(azblob.NewAnonymousCredential(), azblob.PipelineOptions{
		Retry: azblob.RetryOptions{
			TryTimeout: 60 * time.Minute,
		},
	})
	containerURL = azblob.NewContainerURL(*URL, p)
    pbfURL := containerURL.NewBlockBlobURL(path.Join(blobFolder, pbf))
	pbfRes, err := pbfURL.Download(ctx, 0, azblob.CountToEnd, azblob.BlobAccessConditions{}, false)
	if err != nil {
		logging.Error(logTag, "download pbf error: ", err)
		return err
	}
	pbfBody := pbfRes.Body(azblob.RetryReaderOptions{MaxRetryRequests: 5})
	pbfBuffer := bytes.Buffer{}
	_, err = pbfBuffer.ReadFrom(pbfBody)
	if err != nil {
		logging.Error(logTag, "read pbf error: ", err)
		return err
	}

	pbfLocalPath := path.Join(config.UCMConfig.OtMapFolder, pbf)
	err = write(pbfLocalPath, pbfBuffer.Bytes())
`

**Comment by JeffreyRichter** [comment]
In addition to your time out, there is a per-try timeout. Whichever timeout expires first causes the DeadlineExceeded. Make sure the per-try timeout is also set high.

**Comment by JeffreyRichter** [comment]
I looked more closely at your code and you may be setting it correctly. You are passing a ctx into download; maybe that is expiring?

You don't show how it is initialized in your code.

**Comment by zhangtiedong0912** [comment]
do you mean the `ctx` will impact the download? the `ctx` is context , It's passed in by an external function.

**Comment by JeffreyRichter** [comment]
Yes, today is the purpose of the passed-in context, to allow cancellation.

**Comment by zhangtiedong0912** [comment]
let me try to use a new `context.Background()`

**Comment by zhangtiedong0912** [comment]
Thank you sir, you are correct.
