### ISSUE TITLE
serviceURL.SetProperties always fails for Logging properties

### ISSUE THREAD

**Issue by hhempelmann** [Azure/azure-storage-blob-go#166]
### Which version of the SDK was used?
v0.8.0

### Which platform are you using? (ex: Windows, Linux, Debian)
mac

### What problem was encountered?
calling serviceURL.SetProperties for Logging always returns with "storageServiceProperties.Logging.RetentionPolicy" doesn't exist
->
    TestAzureClient: azure_test.go:40: Unexpected error when creating bucket "backupbuckettest47": Failed to enable logging: Failed to set logging properties for container service "https://backupbuckettest47.blob.core.windows.net": -> github.com/Azure/azure-pipeline-go/pipeline.NewError, .../go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.2/pipeline/error.go:159
        validation failed: parameter=storageServiceProperties.Logging.RetentionPolicy constraint=Null value=azblob.RetentionPolicy{Enabled:true, Days:(*int32)(0xc0003e2448)} details: field **"storageServiceProperties.Logging.RetentionPolicy" doesn't exist**
        

### How can we reproduce the problem in the simplest way?
	days := int32(5)
	serviceProperties := azblob.StorageServiceProperties{Logging: &azblob.Logging{Version: "1.0", Read: true, Write: true, Delete: true, RetentionPolicy: azblob.RetentionPolicy{Enabled: true, Days: &days}}}

	_, err := serviceURL.SetProperties(context.Background(), serviceProperties)
	if err != nil {
		return errors.Wrap(err, fmt.Sprintf("Failed to set logging properties for container service %q", serviceURL.String()))
	}

### Have you found a mitigation/solution?
unfortunately not

**Comment by mohsha-msft** [comment]
@hhempelmann 

Thanks for reaching out. Please consider upgrading to the newer version. It doesn't have this problem with it.
