### ISSUE TITLE
project query

### ISSUE THREAD

**Issue by kpfaulkner** [Azure/azure-storage-blob-go#17]
Hi

I've been away from the azure-sdk-for-go project for a while, but just noticed this repo. I'm just wondering how this one is different to the previously used https://github.com/Azure/azure-storage-go/ ?  Is this *purely* for blob storage (and not table/queues etc?)  

Or does it have other aims?

Merely curious, since blob storage is one of my main use of Azure + Go.

Cheers

Ken

**Comment by JeffreyRichter** [comment]
This repo is the “latest & greatest”. It is for blobs only; we will introduce files/queues SDKs later (in their own repos [probably]). This new SDK is a new architecture and has great retry/logging/goroutine safety/context cancellation and many other features.

-- Jeffrey Richter (watch Architecting Distributed Cloud Apps<https://aka.ms/RichterCloudApps> on YouTube<https://aka.ms/RichterCloudApps> or edX<https://aka.ms/edx-devops200_9x-about>)

**Comment by kpfaulkner** [comment]
Thanks... will definitely start looking through it!

**Comment by zezha-msft** [comment]
Wow great! This is organic growth. :)
