### ISSUE TITLE
go.mod doesn't track all project's dependencies

### ISSUE THREAD

**Issue by simonpasquier** [Azure/azure-storage-blob-go#173]
### Which version of the SDK was used?
v0.8.0

### Which platform are you using? (ex: Windows, Linux, Debian)
Linux

### What problem was encountered?

The current `go.mod` doesn't track all project's dependencies which can cause issues for project using this library.

### How can we reproduce the problem in the simplest way?

Run `go mod tidy && git diff` on a fresh cloned copy of the project.

### Have you found a mitigation/solution?
No

**Comment by zezha-msft** [comment]
Sorry for the inconvenience @simonpasquier. This should be fixed in 0.9 now.

**Comment by simonpasquier** [comment]
Thanks a lot!
