### ISSUE TITLE
- Should storage SDK not be used with azblob? - Options functionality in azblob? - Blob storage vs ADLSGen2

### ISSUE THREAD

**Issue by shibanik** [Azure/azure-storage-blob-go#178]
### Which version of the SDK was used?
v0.8.0

### Which platform are you using? (ex: Windows, Linux, Debian)
Windows

### What problem was encountered?
I was working on using the Go SDK for blob storage. I wanted to check about a few things :
- Both the storage sdk and the azblob sdk exist. I saw that the storage one is being deprecated but wanted to confirm that and if no functionality from storage should be used elsewhere in the code that uses azblob at present?
- The storage SDK has options which allow to check if a blob exists beforehand but I didn't see an equivalent in azblob. So I wanted to check if there was something for this in azblob that I had missed.
- Does the implementation for ADLSGen2 vary in any way as compared to blob storage (block)? I couldn't find anything that mentioned it being implemented differently

**Comment by JeffreyRichter** [comment]
To check if a blob exists, just try to get its properties. This is what the Exists function in other languages do. I'll let someone else answer the ADLSGen2 question.

**Comment by zezha-msft** [comment]
Hi @shibanik, thanks for reaching out!

The ADLS Gen2 service has interop with the Blob Storage. So the same data can be written/read from either the `dfs` endpoint or `blob` endpoint. We are going to offer a dedicated ADLS Gen2 SDK.

`azblob` package is the official Storage SDK. 

Please let us know if you have any other question.
