### ISSUE TITLE
correct branch

### ISSUE THREAD

**Issue by kpfaulkner** [Azure/azure-storage-blob-go#18]
Hi

Just wondering which branch is used for development? Is it dev or master? Appears more stuff is happening on master.

Cheers

Ken

**Comment by JeffreyRichter** [comment]
Yes, master


  *   Jeffrey Richter (watch Architecting Distributed Cloud Apps<https://aka.ms/RichterCloudApps> on YouTube<https://aka.ms/RichterCloudApps> or edX<https://aka.ms/edx-devops200_9x-about>)

**Comment by kpfaulkner** [comment]
answered
