### ISSUE TITLE
Scalability benefit over https://github.com/Azure/azure-sdk-for-go?

### ISSUE THREAD

**Issue by meirf** [Azure/azure-storage-blob-go#19]
My workflow includes doing each of these operations concurrently:

Create:
[`PutBlock`](https://godoc.org/github.com/Azure/azure-sdk-for-go/storage#Blob.PutBlock) followed by [`PutBlockList`](https://godoc.org/github.com/Azure/azure-sdk-for-go/storage#Blob.PutBlockList)

Copy:
[`Copy`](https://godoc.org/github.com/Azure/azure-sdk-for-go/storage#Blob.Copy)

Delete:
[`DeleteIfExists`](https://godoc.org/github.com/Azure/azure-sdk-for-go/storage#Blob.DeleteIfExists)

99.9% of my blobs are quite small (<5MB) and fit in one block.

**Are there benefits to using this library instead?**

**Comment by JeffreyRichter** [comment]
The Blob storage code in https://github.com/Azure/azure-sdk-for-go is the old SDK; it is no longer being maintained. This repo contains our new SDK; it is maintained by the storage team. The new SDK handles concurrent operations easily. I don't have knowledge of the old SDK to know how it compares. But, we encourage people to use this new SDK - it is the future.
