### ISSUE TITLE
Cannot set metadata on blobs due to header-name canonicalization

### ISSUE THREAD

**Issue by jwwk** [Azure/azure-storage-blob-go#191]
### Which version of the SDK was used?
v0.10.0

### Which platform are you using? (ex: Windows, Linux, Debian)
*Go:* `go version go1.14.5 darwin/amd64`
For development purposes, I used the [Azurite Service Emulator](https://github.com/Azure/Azurite) as backend.
*Image:* `mcr.microsoft.com/azure-storage/azurite:latest`
*Hash:* `sha256:f1fdee4a45226659c5afa30b8d8d3a479037c701826d32448078f22a7cd011a4`

### What problem was encountered?
I tried to set metadata on a Blob by following [the example from the docs](https://godoc.org/github.com/Azure/azure-storage-blob-go/azblob#example-Metadata--Blobs). However, the new metadata was not saved. Instead, all existing metadata was removed from the blob.
I found out, that the request looks like this:
```
PUT http://localhost:10000/devstoreaccount1/mycontainer/ReadMe.txt?comp=metadata&timeout=61
Authorization: REDACTED
User-Agent: [Azure-Storage/0.10 (go1.14.5; darwin)]
X-Ms-Client-Request-Id: [03a4adbe-1e7c-4530-59b8-4d44c0aaecb1]
X-Ms-Meta-Editor: [Grant]
X-Ms-Version: [2019-02-02]
x-ms-date: [Fri, 17 Jul 2020 08:40:33 GMT]
```

As you can see, all header field names are by default canonicalized (i.e. `Dash-Separated-With-Capital-First-Letter`), since they have been set with the [Request.Header.Add/Set](https://golang.org/src/net/http/header.go) methods. Both methods use [textproto.CanonicalMIMEHeaderKey](https://golang.org/pkg/net/textproto/#CanonicalMIMEHeaderKey).

The only exception to this canonicalized form of `x-ms-...` header field names is `x-ms-date`, which is set like this:
```
headerXmsDate := "x-ms-date"
request.Header[headerXmsDate] = []string{time.Now().UTC().Format(http.TimeFormat)}
```
[modified excerpt from this source](https://github.com/Azure/azure-storage-blob-go/blob/master/azblob/zc_credential_shared_key.go#L54-L57)

Throughout the Azure documentation, all Azure specific header field names are prefixed with `x-ms-` it its lower-case form. The Go SDK however mixes those styles.

I know, that [RFC 7230](https://tools.ietf.org/html/rfc7230#section-3.2) considers header field names to be case-insensitive. Nevertheless, [the Azure documentation states](https://docs.microsoft.com/en-us/rest/api/storageservices/setting-and-retrieving-properties-and-metadata-for-blob-resources#Subheading1), that the backend will consider the case of the metadata field name. However, it is unclear, if this also applies to the header field name prefix `x-ms-meta-`:

> Names are case-insensitive. Note that metadata names preserve the case with which they were created, but are case-insensitive when set or read.

At least for the Azurite storage emulator, the handling of the header field names breaks the functionality of the blob metadata feature and leads to completely unexpected behavior (all metadata being removed).

### How can we reproduce the problem in the simplest way?
Try [the example from the docs](https://godoc.org/github.com/Azure/azure-storage-blob-go/azblob#example-Metadata--Blobs) with an Azurite backend.

### Have you found a mitigation/solution?
I needed to modify the sources of two packages to mitigate the problem:
#### 1. `github.com/Azure/azure-storage-blob-go`
Directly set the metadata headers on the header map instead of using the Add/Set methods
#### 2. `github.com/Azure/azure-pipeline-go`
This package [clones requests at some point](https://github.com/Azure/azure-pipeline-go/blob/master/pipeline/request.go#L85-L90). In that method, I needed to replace the Add method again by modifying the underlying header map

After these modifications, the correctly cased `x-ms-meta-*` headers are passed through the pipeline and the metadata is set on the blob.

### Conclusions
This issue is either a problem of Azurite for not parsing the headers right, or it is a problem of the Golang SDK for not sending the correctly cased header field names. If the first is the case, I can open an issue over at the Azurite repository.

**Comment by philjb** [comment]
I have run into this problem too. I believe it is actually a problem with Azurite and some ambiguity on the Azure Storage docs about casing requirements of `x-ms` headers. I suspect that Azurite is only accepting the full lowercase headers (per the swagger definition) while the real Azure service accepts other casing forms per RFC-7230 (otherwise this go library wouldn't be working for lots more people).

**Comment by jwwk** [comment]
I have fixed the issue in Azurite. It should be resolved with the next Azurite release.
