### ISSUE TITLE
[Question] How to create SAS URLs when using System Managed Identity?

### ISSUE THREAD

**Issue by WhileLoop** [Azure/azure-storage-blob-go#192]
I am using `adal.NewServicePrincipalTokenFromMSI` to create a `azblob.TokenCredential`.  `NewSASQueryParameters` seems to only accept `azblob.StorageAccountCredential`.

How can I generate a SAS URL without using a storage account key on Azure VM with a System Managed Identity?

**Comment by nohajc** [comment]
I would also like to know how to do this. I'm having trouble finding any relevant documentation.

**Comment by zezha-msft** [comment]
Please refer to the tests: https://github.com/Azure/azure-storage-blob-go/blob/master/azblob/zt_user_delegation_sas_test.go#L87
