### ISSUE TITLE
Add support for the Find Blobs By Tag API? 

### ISSUE THREAD

**Issue by plombardi89** [Azure/azure-storage-blob-go#193]
### Which version of the SDK was used?

v0.9.0

### Which platform are you using? (ex: Windows, Linux, Debian)

Linux

### What problem was encountered?

The Find Blobs By Tag API is not implemented: https://docs.microsoft.com/en-us/rest/api/storageservices/find-blobs-by-tags

### How can we reproduce the problem in the simplest way?

Not implemented.

### Have you found a mitigation/solution?

Please implement it :)

**Comment by mohsha-msft** [comment]
Linking similar feature-request here: https://github.com/Azure/azure-storage-blob-go/issues/206

**Comment by mohsha-msft** [comment]
Hey @plombardi89 

Thanks for reaching out. Support for Set Tags/Get Tags/Find Blob by Tags has been added in the recent release. Please checkout [release logs](https://github.com/Azure/azure-storage-blob-go/releases/tag/v0.11.0) to know more
