### ISSUE TITLE
Project fails to compile

### ISSUE THREAD

**Issue by ehotinger** [Azure/azure-storage-blob-go#20]
Seems like even a basic example fails to compile for me, likely due to the constraint on the `azure-pipeline-go` library.

- Sample Gist: https://gist.github.com/ehotinger/9589082621a692aba6668ea820ea1c6a
- Run `dep init`
- Run `dep ensure`
- Run `go build -v`

> vendor/github.com/Azure/azure-storage-blob-go/2016-05-31/azblob/credential_anonymous.go:15:21: undefined: pipeline.FactoryFunc

`$ dep status`
> PROJECT                                 CONSTRAINT  VERSION  REVISION  LATEST  PKGS USED
> github.com/Azure/azure-pipeline-go      1.1.3       1.1.3    f4da77e   1.1.3   1
> github.com/Azure/azure-storage-blob-go  ^0.1.2      0.1.2    c91e48a   0.1.2   1

Also tested a build directly against `master` - same issue.

---

EDIT: this is because of the 1.1.3 constraint put in the project for `azure-pipeline-go`. It needs to be 1.1.4; the upstream source is out of sync.

**Comment by JeffreyRichter** [comment]
The toml file might be bad. Use go get and let me know if you have problems.

-- Jeffrey Richter (watch Architecting Distributed Cloud Apps<https://aka.ms/RichterCloudApps> on YouTube<https://aka.ms/RichterCloudApps> or edX<https://aka.ms/edx-devops200_9x-about>)
________________________________

**Comment by ehotinger** [comment]
Yeah, it's broken from the `1.1.3` dependency. I made a separate issue on the other repo because `dep` won't automatically update to `0.1.4` - you have to force it to hit the latest commit @ master. Not sure if the `0.1.4` was a typo or intentional to downgrade from `1.0`.
