### ISSUE TITLE
Add support for Get/Set Blob Tags

### ISSUE THREAD

**Issue by seungjin-clumio** [Azure/azure-storage-blob-go#206]
### Which version of the SDK was used?
0.10.0

### Which platform are you using? (ex: Windows, Linux, Debian)
Darwin

### What problem was encountered?
[Get](https://docs.microsoft.com/en-us/rest/api/storageservices/get-blob-tags)/[Set](https://docs.microsoft.com/en-us/rest/api/storageservices/set-blob-tags) Blob Tags is implemented in REST but not here

### How can we reproduce the problem in the simplest way?
It's not implemented

### Have you found a mitigation/solution?
Please implement it

**Comment by mohsha-msft** [comment]
Hey @seungjin-clumio 

Thanks for reaching out. Support for Set Tags/Get Tags/Find Blob by Tags has been added in the recent release. Please checkout [release logs](https://github.com/Azure/azure-storage-blob-go/releases/tag/v0.11.0) to know more
