### ISSUE TITLE
Upload operations to support tags

### ISSUE THREAD

**Issue by seungjin-clumio** [Azure/azure-storage-blob-go#208]
Blob service `Put Blob` [operation](https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob#request) can optionally take tags as part of the request. This SDK contains various (helper) functions to put a blob, and allowing tags to be passed into them would be useful and appreciated.

### Which version of the SDK was used?
v 0.10.0

### Have you found a mitigation/solution?

Given an implementation of `Set Blob Tags` (#206) it's possible to create the blob first and set tags later. However, if desired set of tags are known at the time of put, allowing tags in Put Blob can consolidate this process into a single request.

**Comment by mohsha-msft** [comment]
@seungjin-clumio ,

Thanks for reaching out. The capabilities to add tags when uploading the blob has been added. Furthermore, we have added Get Tags/Set Tags/Find Blobs by Tags API support in the newest release as well. 

Please refer to [release logs](https://github.com/Azure/azure-storage-blob-go/releases/tag/v0.11.0) for more information. Feel free to reach out for more information.
