### ISSUE TITLE
Could not get http status if an error was encountered (Download and UploadBufferToBlockBlob)

### ISSUE THREAD

**Issue by charliedmcb** [Azure/azure-storage-blob-go#210]
### Which version of the SDK was used?
github.com/Azure/azure-storage-blob-go v0.0.0-20190123011202-457680cc0804
https://github.com/Azure/azure-storage-blob-go/tree/457680cc0804810f6d02958481e0ffdda51d5c60

### Which platform are you using? (ex: Windows, Linux, Debian)
Linux

### What problem was encountered?
Both of the methods ```(b BlobURL) Download``` in url_blob.go and ```azblob.UploadBufferToBlockBlob``` in highlevel.go return nil for the http response if any error is encountered.

I was hoping to check the response status for 404 on Download, and 412 on upload. However, the status was not accessible 

### How can we reproduce the problem in the simplest way?
Try to use either of the methods described above to get check some error response status that would return an error 

### Have you found a mitigation/solution?
I used a string comparison, but am not satisfied with that solution. Is there a better way to do this I missed?

**Comment by mohsha-msft** [comment]
Hey @charliedmcb!

The issue has been addressed in the recent releases. Please consider upgrading to the latest release. 😄
