### ISSUE TITLE
Credential from connectionstring

### ISSUE THREAD

**Issue by guilhem** [Azure/azure-storage-blob-go#211]
### Which version of the SDK was used?

v0.10.0

### Which platform are you using? (ex: Windows, Linux, Debian)

Linux

### What problem was encountered?

No function to get credential object from a connection string

### Have you found a mitigation/solution?

We use some part of legacy sdk storage: https://github.com/Azure/azure-sdk-for-go/blob/master/storage/client.go#L222

**Comment by zezha-msft** [comment]
Thanks for reaching out! We'll track this with #244.
