### ISSUE TITLE
Release cadence

### ISSUE THREAD

**Issue by elsesiy** [Azure/azure-storage-blob-go#215]
It's unclear for SDK users how often new releases are cut and what the release schedule looks like.

Right now there's quite a few pending changes in `dev` since July incl. API version updates so it would be beneficial to know when these will land in `0.11.0`.
There's no tracked milestone for an upcoming release either, so can you please document the process this repo is following?

Thanks.

**Comment by mohsha-msft** [comment]
Hey @elsesiy 

Thanks for reaching out to us. We've release `0.11.0` and all the pending API changes which were in dev branch have now been merged with the master. Please refer to [release logs](https://github.com/Azure/azure-storage-blob-go/releases/tag/v0.11.0) for more information. We apologize for the delay caused at our end.

**Comment by elsesiy** [comment]
@mohsha-msft Thank you for the update but that doesn't address the issue per se. Can you please provide users of the library with information on how frequent releases are done?
