### ISSUE TITLE
error thrown when blob doesn't exist

### ISSUE THREAD

**Issue by jjjj2020** [Azure/azure-storage-blob-go#219]
### Which version of the SDK was used?
latest version as of 10/23/2020
### Which platform are you using? (ex: Windows, Linux, Debian)
windows
### What problem was encountered?
 github.com/Azure/azure-storage-blob-go/azblob.newStorageError, C:/Users/xxxx/go/src/github.com/Azure/azure-storage-blob-go/azblob/zc_storage_error.go:42

get, err := blockBlobURL.Download(ctx, 0, 0, azblob.BlobAccessConditions{}, false)

error is thrown from the above line of code. The error should be wrapped inside the err but it's not, and caused the gRPC server shut down.
### How can we reproduce the problem in the simplest way?

choose anonymous account, then try to download a file that doesn't exist.
        credential := azblob.NewAnonymousCredential()
	blockBlobURL := azblob.NewBlockBlobURL(*u, azblob.NewPipeline(credential, azblob.PipelineOptions{}))	
	ctx := context.Background()
	// Download the blob's contents and verify that it worked correctly
	get, err := blockBlobURL.Download(ctx, 0, 0, azblob.BlobAccessConditions{}, false)

### Have you found a mitigation/solution?
not yet. looking for fix.

**Comment by mohsha-msft** [comment]
Inactive. 
Please reopen and reach out if issue persists
