### ISSUE TITLE
[question] ADLS Gen2 API interop

### ISSUE THREAD

**Issue by vijayrajah** [Azure/azure-storage-blob-go#222]
### Which version of the SDK was used?
v0.10.0

### Which platform are you using? (ex: Windows, Linux, Debian)
Windows & Linux

what is the GO SDK equivalent for Gen2 filesystems & Path operations? ( as specified here https://docs.microsoft.com/en-us/rest/api/storageservices/data-lake-storage-gen2 ). 

Does this SDK also support interop with these filesystems & path operations? (If so what are the API to use? )

-Vijay

**Comment by backerman** [comment]
Hierarchical storage requires the `resource=filesystem` and `recursive=(true|false)` query parameters, which aren't yet exposed in this package.

**Comment by mohsha-msft** [comment]
As @backerman mentioned, we're working on new SDKs to provide support for ADLS Gen2 APIs. Current SDK only supports Blob Storage and not Gen2 storage.

**Comment by jeffshuang** [comment]
@mohsha-msft  Just to confirm this SDK does not support hierarchical storage and the new SDKs that provide support for ALDS Gen2 are not available yet?

**Comment by mohsha-msft** [comment]
Yes you're right @jeffshuang. ADLS Gen2 SDK isn't available right now.

As mentioned in the previous comment, we're currently working on new Blob SDK, File SDK, ADLS Gen2 SDK which will offer more reliability. We're going to make Blob SDK in preview soon.
