### ISSUE TITLE
Breaking changes in the API

### ISSUE THREAD

**Issue by ncw** [Azure/azure-storage-blob-go#226]
I recently updated the azure-storage-blob-go  from v0.10.0 to v0.11.0

```
-	github.com/Azure/azure-storage-blob-go v0.10.0
+	github.com/Azure/azure-storage-blob-go v0.11.0
```

In commit 146595a6f8245e5c920d19266a4616f70d72f366 

`azblob.BlobItem` was renamed to `azblob.BlobItemInternal`

```diff
// BlobItem - An Azure Storage blob
-type BlobItem struct {
+// BlobItemInternal - An Azure Storage blob
+type BlobItemInternal struct {
``` 

This is a fairly major breaking change in the API! `BlobItem` being the most important data structure for users representing an Azure blob.

This isn't in the breaking changes documentation: https://github.com/Azure/azure-storage-blob-go/blob/master/BreakingChanges.md and I think it probably should be.

I also noticed that these functions gained extra arguments.

- `BlockBlobURL.CommitBlockList`
- `BlockBlobURL.StartCopyFromURL`

Neither of these changes were particularly difficult to fix however having libraries with unstable APIs is a maintenance burden.

Will this library get a 1.0 release to gain API stability?

Thank you for your good work :-)

**Comment by mohsha-msft** [comment]
Hey @ncw 

Thanks for reaching out. Yes, this should have been mentioned in the breaking changes and thanks for pointing it out. As we've moved toward supporting newer service version i.e. `2019-12-12`, almost all the API calls have updates in their function signature. I'll make sure to document it.

**Comment by ncw** [comment]
Thanks for your informative answer @mohsha-msft . Good luck with a stable release - I shall look forward to it :-)
