### ISSUE TITLE
install error on mac

### ISSUE THREAD

**Issue by meirf** [Azure/azure-storage-blob-go#23]
Running `$ go get github.com/Azure/azure-storage-blob-go/2016-05-31/azblob`

gives me this output
```
# github.com/Azure/azure-storage-blob-go/2016-05-31/azblob
gocode/src/github.com/Azure/azure-storage-blob-go/2016-05-31/azblob/highlevel.go:164:7: undefined: mmf
gocode/src/github.com/Azure/azure-storage-blob-go/2016-05-31/azblob/highlevel.go:166:12: undefined: newMMF
```

My environment:
```
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mfischer/alpha/gocode"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9.3/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/mm/q2bf08hn361bhqqq5wy38ssc0000gn/T/go-build111810440=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

```

**Edit:
oh I see there are files for windows/linux but none for mac. I'll comment out that code since looks like only used as example.**

**Comment by meirf** [comment]
Oh. I see there are `mmap_windows.go` and `mmap_linux.go` but no similar file for mac

**Comment by meirf** [comment]
Are there plans to support this library on osx?

**Comment by JeffreyRichter** [comment]
Yes, we will. For now, rename mmap_linux.go to mmap_darwin.go and you should be good. I have the fix for this but it is not checked in yet.

**Comment by brusMX** [comment]
Actually the file name has changed
```bash

mv mmf_darwin_linux.go mmf_darwin.go
```

**Comment by shanebarnes** [comment]
Renaming the file with a "_unix" suffix should allow for successful builds targeting both darwin and linux:

`mv mmf_darwin_linux.go mmf_unix.go`

**Comment by JeffreyRichter** [comment]
Renaming to mmf_unix.go will break the build on Windows. However, I think I fixed this awhile a go by adding "// +build linux darwin" to the .go file.

**Comment by shanebarnes** [comment]
According to the documentation (https://golang.org/pkg/go/build/#overview), using a conditional compilation suffix should take the following form: source_<GOOS>_<GOARCH>.go (e.g., source_windows_amd64.go). So using the build tags is appropriate in this case but the file suffix must not trigger an implicit conditional compilation.

**Comment by JeffreyRichter** [comment]
If you run "go tool dist list", you'll see the list of supported GOOS/GOARC combinations. "unix" is not on the list at all and therefore not a supported GOOS. So, a file name ending with "_unix.go" is ALWAYS compiled by the compiler regardless of the GOOS. This is why I MUST add "// +build linux darwin" to the top of my file. Alternatively, I could have to files with identical contents but one named mmf_darwin.go and the other named mmf_linux.go. I prefer the 1 file so I don't have to make similar changes in multiple files.
