### ISSUE TITLE
verifying github.com/Azure/azure-storage-blob-go@v0.12.0: checksum mismatch

### ISSUE THREAD

**Issue by h-no** [Azure/azure-storage-blob-go#237]
### Which version of the SDK was used?
0.11.0, trying to upgrade to 0.12.0

### Which platform are you using? (ex: Windows, Linux, Debian)
Ubuntu 18.04, MacOS

### What problem was encountered?
Dependabot updates my packages, but encountered an error:
```
verifying github.com/Azure/azure-storage-blob-go@v0.12.0: checksum mismatch
	downloaded: h1:7bFXA1QB+lOK2/ASWHhp6/vnxjaeeZq6t8w1Jyp0Iaw=
	go.sum:     h1:LEu0WO1uxAkeJFuNTZR+xxUpIoRUwOXgA2ipS798Ycc=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```
I get the same error locally when trying to update from the Pull Request Dependabot created.
I tried `go clean -modcache` & `go mod tidy` but the same error persists.

Did you move the tag or something? Thinking that maybe Dependabot pulled in the change, then perhaps you re-created 0.12.0?

### How can we reproduce the problem in the simplest way?
Not sure, tbh.

### Have you found a mitigation/solution?
Removing `go.sum` and re-creating it solves the problem. But it seems strange that I encountered this issue in the first place and wanted to see if you can shed some light on it...

**Comment by mohsha-msft** [comment]
Hey @h-no ,

Thanks for reaching out!
Please try `go get github.com/Azure/azure-storage-blob-go`. It will automatically fetch the latest version i.e. 0.12.0. After that you can run `go mod tidy`

**Comment by h-no** [comment]
> Hey @h-no ,
> 
> Thanks for reaching out!
> Please try `go get github.com/Azure/azure-storage-blob-go`. It will automatically fetch the latest version i.e. 0.12.0. After that you can run `go mod tidy`
> 
> As for the error you mentioned, it is mentioned well [here](https://github.com/golang/go/issues/33665)

@mohsha-msft  I wasn't wondering how to fix it, I wondered why it happened in the first place.

From your link, I assume you refer to `go help module-auth` as I mentioned that `go clean -modcache` didn't help.
`go help module-auth` says:
```
If the go command reports a mismatch in go.sum, the downloaded code
for the reported module version does not match the one used in a
previous build of the main module. It is important at that point
to find out what the right checksum should be, to decide whether
go.sum is wrong or the downloaded code is wrong. Usually go.sum is right:
you want to use the same code you used yesterday.
```
```
If a go.sum mismatch is reported, it is always worth investigating why
the code downloaded today differs from what was downloaded yesterday.
```

So my guess is that you moved the tag.

**Comment by mohsha-msft** [comment]
@h-no ,

It's very peculiar for me as well because when I did fetch v0.12.0 in another project I work on, it didn't cause me checksum mismatch. Same is the case with my other peers. So I was wondering what may have caused this as well.  Let me find what may have caused this and get back to you

**Comment by h-no** [comment]
Thanks, @mohsha-msft 

Some info that may help:

My Dependabot ran Sun Dec 13 05:19:35 2020 +0000
It pulled in:
```
-github.com/Azure/azure-storage-blob-go v0.11.0 h1:WCTHKKNkHlzm7lzUNXRSD11784LwJqdrxnwWJxsJQHg=
-github.com/Azure/azure-storage-blob-go v0.11.0/go.mod h1:A0u4VjtpgZJ7Y7um/+ix2DHBuEKFC6sEIlj0xc13a4Q=
+github.com/Azure/azure-storage-blob-go v0.12.0 h1:LEu0WO1uxAkeJFuNTZR+xxUpIoRUwOXgA2ipS798Ycc=
+github.com/Azure/azure-storage-blob-go v0.12.0/go.mod h1:A0u4VjtpgZJ7Y7um/+ix2DHBuEKFC6sEIlj0xc13a4Q=
```
And now `LEu0WO1uxAkeJFuNTZR+xxUpIoRUwOXgA2ipS798Ycc=` doesn't match anymore as `7bFXA1QB+lOK2/ASWHhp6/vnxjaeeZq6t8w1Jyp0Iaw=`is being downloaded for 0.12.0 instead.
