### ISSUE TITLE
Any way to check error using DownloadBlobToFile function to know if the blob doesn't exists?

### ISSUE THREAD

**Issue by jfcalvo** [Azure/azure-storage-blob-go#258]
### Which version of the SDK was used?

`v0.13.0`

### Which platform are you using? (ex: Windows, Linux, Debian)

macOS Mojave.

### What problem was encountered?

This is more a question than a problem.

I'm using `DownloadBlobToFile` function to directly download a blob to a local file. I would like to know if there is a correct way to detect that the blob doesn't exists (checking the error returned or something similar) avoiding an explicit previous request to check if the blob exists or not.

I have not found specific error types defined in the library.

### How can we reproduce the problem in the simplest way?

Nothing to reproduce.

### Have you found a mitigation/solution?

No.

**Comment by siminsavani-msft** [comment]
Hi there! The DownloadBlobToFile will return an error if the blob does not exist. You could utilize this error to determine if blob does not exist.

Here's an example: 
https://github.com/Azure/azure-storage-blob-go/blob/d80c8c7c7c4385e4afe4ebdaab9b31efd7d87eb1/azblob/zt_examples_test.go#L1067

Please let me know if you have any questions!
