### ISSUE TITLE
Question on release versions

### ISSUE THREAD

**Issue by caseyhadden** [Azure/azure-storage-blob-go#261]
Hi,

We're looking to incorporate this library into a project. When looking at which release, all except v0.11.0 and v0.12.0 are marked as pre-release. Is there an actual difference in these vs. v0.13.0 or is the pre-release flag just erroneously missing for those releases?

Given the overall v0 status, both of those releases being from one individual, and other releases are pre-release it wasn't immediately clear whether this was a true status or missed checkbox during the release process.

Thanks.
Casey

**Comment by zezha-msft** [comment]
Thanks for reaching out @caseyhadden, you are right the library is still in preview and pre-release flag was not set correctly.

Please let us know if you have any other question or concern.
