### ISSUE TITLE
[question]how to check if container is already created in storage account using azblob

### ISSUE THREAD

**Issue by mayguptMSFT** [Azure/azure-storage-blob-go#262]

**Comment by mohsha-msft** [comment]
@mayguptMSFT ,

There are multiple ways to do that. For instance, did you try using [containerUrl.GetProperties()](https://github.com/Azure/azure-storage-blob-go/blob/d80c8c7c7c4385e4afe4ebdaab9b31efd7d87eb1/azblob/url_container.go#L106). It should return an error "ContainerNotFound" if container doesn't exist. Alternatively you can use [serviceUrl.ListContainersSegment()](https://github.com/Azure/azure-storage-blob-go/blob/d80c8c7c7c4385e4afe4ebdaab9b31efd7d87eb1/azblob/url_service.go#L106) to list containers in storage account.
