### ISSUE TITLE
InvalidBlockList when concurrently writing to the same key

### ISSUE THREAD

**Issue by marwan-at-work** [Azure/azure-storage-blob-go#263]
### Which version of the SDK was used?
v0.11.0

### Which platform are you using? (ex: Windows, Linux, Debian)
Darwin

### What problem was encountered?
Given the below code snippet (using gocloud.dev, which uses this library):

```golang
azbucket, err := azureblob.OpenBucket(ctx, pipeline, accountName, containerName, &azureblob.Options{Credential: credential})

var wg sync.WaitGroup
wg.Add(3)
for i := 0; i < 3; i++ {
	go func() {
		defer wg.Done()
		err := azbucket.WriteAll(ctx, "conctest/data", []byte("hello"), &blob.WriterOptions{})
		fmt.Println("WROTE DATA", err)
	}()
}
wg.Wait()
```

Only 1 of the 3 writes succeeds while the other 1 or 2 will almost certainly return a 400 error stating an InvalidBlockList. 

However, when reading the following docs:  https://docs.microsoft.com/en-us/azure/storage/blobs/concurrency-manage?tabs=dotnet

It explicitly says that: 

> If you don't explicitly specify a strategy, then by default the last writer wins.

Would love to confirm if this SDK specifies a non-default strategy and if not, I believe this would be then categorized as a bug either on the SDK or the storage API side? 

Thanks!

### How can we reproduce the problem in the simplest way?
With the snippet provided above. 

### Have you found a mitigation/solution?
I am considering simply ignoring all InvalidBlockList errors, but I want to make sure that that is an appropriate mitigation.

**Comment by jlohiya** [comment]
We are facing same issue when using minio azure gateway. 

is it possible to prioritize this?

**Comment by marwan-at-work** [comment]
Any updates here?

**Comment by marwan-at-work** [comment]
cc: @siminsavani-msft @zezha-msft

**Comment by zezha-msft** [comment]
answered here: https://github.com/Azure/azure-sdk-for-go/issues/18490
