### ISSUE TITLE
Question about handling error conditions

### ISSUE THREAD

**Issue by DarcInc** [Azure/azure-storage-blob-go#278]
### Which version of the SDK was used?
0.13.0

### Which platform are you using? (ex: Windows, Linux, Debian)
Linux

### What problem was encountered?
Not a problem, a question.

The response object appears to be only returned on success.  So it's always going to have (basically) 200/Ok as the status information.  However, if there's a error, there's no good way to get the error details.  From an API design standpoint, it would make sense to include this in the response along with the err result not being nil.  That way I could distinguish a 404 (for example) from some other 40x or 50x error.  

The returned error object appears to contain the information I'd need but it's an internal type.  I could search the resulting text for key phrases, but that seems less than ideal.  If either the error type were exposed so I could cast out to a storageError or the response were always returned with the status and error code set appropriately, I could make intelligent decisions in code to mitigate the problem.

```golang
    resp, err := containerUrl.Create(ctx, azblob.Metadata{}, azblob.PublicAccessNone)
    if err != nil {
        if resp != nil {
            // resp on error appear to be always nil, so we never visit this branch
            log.Printf("%s: %d\n", resp.Status(), resp.StatusCode())
        }
        log.Printf("Unable to create container: %v\n", err)
    }
```
Likewise, this code also fails with a 404, but I can't tell that the container does not exist:
```golang

props, err := containerUrl.GetProperties(ctx, azblob.LeaseAccessConditions{})
if err != nil {
    if props != nil {
        // resp is nil on error so we don't visit this branch.
        log.Printf("Status: %s Error: %s\n", props.Status(), props.ErrorCode())
    }
    log.Printf("Unable to get properties: %v\n", err)
    os.Exit(1)
}
```
### How can we reproduce the problem in the simplest way?
Not an error - a question about a design choice.

### Have you found a mitigation/solution?
There is no good work around other than guess why the call failed and try again.  Or have a human being look at a log/portal.  Or ditch the Go API and make native HTTP calls (yuck).

**Comment by yaegashi** [comment]
Hi @DarcInc,  I've just come to this problem.

Indeed `storageError` is an internal type but it implements [StorageError interface](https://pkg.go.dev/github.com/Azure/azure-storage-blob-go/azblob#StorageError) so you can try the type assertion on it.  There's also [an example](https://pkg.go.dev/github.com/Azure/azure-storage-blob-go/azblob#example-StorageError) in the document.

```go
	_, err = containerURL.Create(ctx, azblob.Metadata{}, azblob.PublicAccessNone)
	if err != nil {
		// ignore err if it indicates the container already exists
		storageErr, ok := err.(azblob.StorageError)
		if !ok || storageErr.Response().StatusCode != http.StatusConflict {
			return err
		}
	}
```
