### ISSUE TITLE
List containers in azurite fails

### ISSUE THREAD

**Issue by sveinung-r** [Azure/azure-storage-blob-go#279]
### Which version of the SDK was used?
v0.13.0

### Which platform are you using? (ex: Windows, Linux, Debian)
Debian

### What problem was encountered?
Listing containers in Azurite fails due to empty include query parameter. This works against Azure blob storage but fails for Azurite. 

According to the blob storage API documentation this should be include={metadata,deleted}, so Azurite is actually in a way right to reject such requests.

I assume that the include parameter should not be present at all when it is not used.

### How can we reproduce the problem in the simplest way?
Run list containers against azurite.

**Comment by mohsha-msft** [comment]
Hey @sveinung-r ,

Sorry for the delayed response.
The default service version of Azurite is generally older as compared to the default service version SDK uses (`2020-04-08`) which can explain the abnormal behavior.

As for your query, both 
`ListContainersSegment(context.Background(), Marker{}, ListContainersSegmentOptions{Prefix: name})`
and  `serviceURL.ListContainersSegment(context.Background(), Marker{}, ListContainersSegmentOptions{Detail: ListContainersDetail{}, Prefix: name})` work just fine.

**Comment by sveinung-r** [comment]
According to the Azure blob API documentation:

include={metadata,deleted} is Optional. Specifies one or more datasets to include in the response.

So this parameter should have _one or more_ values if present. This is as far as I know the case for all API versions.

**Comment by mohsha-msft** [comment]
Hey @sveinung-r ,

I tried running both the statements I mentioned above and it worked, as expected.

To check the right behaviour of service, please find the documentation corresponding your Service API Version

**Comment by sveinung-r** [comment]
It works as expected against Azure blob store, but not against Azurite. 

You can argue that Azurite should mirror the Azure behavior in this case, but since it actually adheres to the API spec it is not unreasonable for them to reject the query.
