### ISSUE TITLE
How to check if a container or blob existing?

### ISSUE THREAD

**Issue by mikecheng11** [Azure/azure-storage-blob-go#280]
### Which version of the SDK was used?
0.13

### Which platform are you using? (ex: Windows, Linux, Debian)
Linux

### What problem was encountered?
How to check if a container or blob existing?

### Have you found a mitigation/solution?
use  c.GetProperties() , if it return error is ServiceCodeContainerNotFound, the container is not existing.

**Comment by mohsha-msft** [comment]
Hi @mikecheng11 ,

There are multiple ways to do that.

Method 1: List API Call
1. Create a `ServiceURL` and do a [ListContainersSegment](https://github.com/Azure/azure-storage-blob-go/blob/d80c8c7c7c4385e4afe4ebdaab9b31efd7d87eb1/azblob/url_service.go#L106) call with appropriate prefix to check if container exists or not.
2. Similarly,  you can create a `ContainerURL`  and perform a [ListBlobsFlatSegment](https://github.com/Azure/azure-storage-blob-go/blob/d80c8c7c7c4385e4afe4ebdaab9b31efd7d87eb1/azblob/url_container.go#L236) call with appropriate filters to check if blob exists

Method 2: GetProperties
1. Create `ContainerURL`/`BlobURL` whose existence you want to verify and perform GetProperties call. If error contains [ContainerNotFound](https://github.com/Azure/azure-storage-blob-go/blob/d80c8c7c7c4385e4afe4ebdaab9b31efd7d87eb1/azblob/service_codes_blob.go#L46) or [BlobNotFound](https://github.com/Azure/azure-storage-blob-go/blob/d80c8c7c7c4385e4afe4ebdaab9b31efd7d87eb1/azblob/service_codes_blob.go#L14)
