### ISSUE TITLE
The start and end in PageRange Struct should be int64

### ISSUE THREAD

**Issue by giventocode** [Azure/azure-storage-blob-go#29]
The start and end of a page range are int32, with a maximum value of 2147483647. This limits a page offset at only ~2.14 GB.  Instead they should be int64.

https://github.com/Azure/azure-storage-blob-go/blob/38ca054dbe15000254766ebc6d91d5497cadaf2b/2016-05-31/azblob/zz_generated_models.go#L2500

**Comment by JeffreyRichter** [comment]
Yes, this is a bug in our swagger file. We have fixed it there but we need to run it through autorest to generate a new models files. I think we’ll push the fix next week.


  *   Jeffrey Richter (watch Architecting Distributed Cloud Apps<https://aka.ms/RichterCloudApps> on YouTube<https://aka.ms/RichterCloudApps> or edX<https://aka.ms/edx-devops200_9x-about>)

**Comment by JeffreyRichter** [comment]
This issue has been resolved.
