### ISSUE TITLE
Azure/azure-storage-go split 

### ISSUE THREAD

**Issue by FrenchBen** [Azure/azure-storage-blob-go#35]
I can understand the need to split the different packages, as announced on the roadmap. 
https://azure.microsoft.com/en-us/blog/preview-the-new-azure-storage-sdk-for-go-storage-sdks-roadmap/
![](https://user-images.githubusercontent.com/3965324/37797367-d67ceeac-2dd6-11e8-99af-5bb3693ceb66.gif)

What I find VERY inconvenient it to simply remove the entire GO SDK library for storage, before the split is even in place. 

### Expected
* https://github.com/Azure/azure-storage-blob-go ✅ 
* https://github.com/Azure/azure-storage-file-go ✅ 

### Actual
* https://github.com/Azure/azure-storage-blob-go ✅ 
* https://github.com/Azure/azure-storage-file-go ❌ 
![](https://media1.giphy.com/media/o7OChVtT1oqmk/giphy.gif)

If I make a parallel to what was done with PHP, the following exist:
* https://github.com/Azure/azure-storage-blob-php
* https://github.com/Azure/azure-storage-file-php
*but* the parent repo still exists: https://github.com/Azure/azure-storage-php

![](https://media3.giphy.com/media/KVFZEmzfbpb2saWAvP/giphy.gif)
Where is the GO File Storage SDK???

**Comment by JeffreyRichter** [comment]
The file go SDK never existed. We are in the process of creating it and we hope to put it into public preview by the end of this month.

-- Jeffrey Richter (watch Architecting Distributed Cloud Apps<https://aka.ms/RichterCloudApps> on YouTube<https://aka.ms/RichterCloudApps> or edX<https://aka.ms/edx-devops200_9x-about>)
________________________________

**Comment by FrenchBen** [comment]
@JeffreyRichter pretty sure it was part of the previous `Azure/azure-storage-go` as this is the package I used to interact with Azure's file storage. 
Either way removing a package completely, instead of renaming/redirecting, is  🙅‍♂️

**Comment by seguler** [comment]
@FrenchBen any thoughts on the repository location ? Would you have preferred if all of these repos are part of Azure SDK for Go repository ?

**Comment by FrenchBen** [comment]
@seguler I would've imagined the split to follow the current PHP/Java pattern.
Keep: github.com/Azure/azure-storage-go up and running (don't break people's build)
Meanwhile, create:
* github.com/Azure/azure-storage-blob-go
* github.com/Azure/azure-storage-file-go
* github.com/Azure/azure-storage-<insert-azure-storage-service>-go

**Comment by joshgav** [comment]
@frenchben I think the contents of Azure/azure-storage-go are now at https://github.com/Azure/azure-sdk-for-go/tree/master/storage, perhaps you can just update your import statement to `github.com/Azure/azure-sdk-for-go/storage`?

**Comment by FrenchBen** [comment]
@joshgav that's what I had to do; except it also force to refactor part of the code as well, as we had pinned a specific commit. 
The fact that the package is marked as `preview` but then immediately `deprecated` is not encouraging. 

The solutions exist, this is more of a rant, and highlight, around how 1 language's SDK was handled, compared to others, and how this could be done differently(better?) in the future.

**Comment by imjosh** [comment]
What I find VERY inconvenient is that I have only 44 more days to migrate off docker cloud and I've spent the last several hours trying to run this problem down. It didn't help that I didn't originally see issue #55 because you closed it (why? it's not fixed).
