### ISSUE TITLE
Storage Soft Delete Support

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-storage-blob-go#37]
(ported from https://github.com/Azure/azure-sdk-for-go/issues/1504)

Hello,

Could we get support for Storage Soft Delete?

https://azure.microsoft.com/en-us/blog/soft-delete-for-azure-storage-blobs-now-in-public-preview/
https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-soft-delete

Thank you.

**Comment by JeffreyRichter** [comment]
This is supported in the 2018-03-28 service API version.

**Comment by techiechap** [comment]
can someone pls share the Storage account soft delete configuration block
