### ISSUE TITLE
How would I stream upload a 10 GB file with configurable concurrency / chunk sizes?

### ISSUE THREAD

**Issue by marstr** [Azure/azure-storage-blob-go#39]
> In Azure-Samples/azure-sdk-for-go-samples#118 says @derekperkins:
It's pretty obvious with S3 and GCS, but I can't figure out how to do that with Azure. Even uploading a simple small file isn't very obvious, since the storage package combines all the messaging, table and blob components.
>
>S3 https://godoc.org/github.com/aws/aws-sdk-go-v2/service/s3/s3manager#Uploader.UploadWithContext
GCS https://godoc.org/cloud.google.com/go/storage#Writer

Copying it here to the more relevant repository.

**Comment by JeffreyRichter** [comment]
Call this package's UploadFileToBlockBlob function.

**Comment by marstr** [comment]
For the lazy:
https://github.com/Azure/azure-storage-blob-go/blob/cf023500f0ffb9fafbb8087be2bd0868559a2c41/2016-05-31/azblob/highlevel.go#L158

https://github.com/Azure/azure-storage-blob-go/blob/c252c656c5c72864f7e433691b308585e6f0c240/2017-07-29/azblob/highlevel.go#L157

**Comment by derekperkins** [comment]
Yeah, the `UploadFileToBlockBlob` is exactly what I'm looking for. When I originally asked the question a few months ago, the main Go sdk didn't point to this repo. I don't fully understand the reasoning for developing storage separate from the rest of the SDK, but I appreciate you pointing me in the right direction.
