### ISSUE TITLE
syscall and Windows

### ISSUE THREAD

**Issue by kpfaulkner** [Azure/azure-storage-blob-go#41]
Hi

It's been a while since I looked at the repo, and I see that mmap_unix.go and mmap_windows.go use various syscall constants which do not exist in Windows.

example output:

go build ./...

# azure-storage-blob-go-microsoft/azure-storage-blob-go/2017-07-29/azblob
.\mmap_unix.go:11:17: undefined: syscall.PROT_READ
.\mmap_unix.go:11:36: undefined: syscall.MAP_SHARED
.\mmap_unix.go:13:17: undefined: syscall.PROT_READ
.\mmap_unix.go:13:35: undefined: syscall.PROT_WRITE
.\mmap_unix.go:13:55: undefined: syscall.MAP_SHARED

etc

Am I missing something? (wrong Go version? 3rd party deps etc?)

Any advice appreciated.

Cheers

Ken

**Comment by JeffreyRichter** [comment]
We have lots of changes/improvements that we are working on and we hope to check in new code very soon (maybe later this week).
I think the version of mmap_unix.go you have is missing this line at the very top:
// +build linux darwin

This will prevent it from being compiled for Windows.


  *   Jeffrey Richter (watch Architecting Distributed Cloud Apps<https://aka.ms/RichterCloudApps> on YouTube<https://aka.ms/RichterCloudApps> or edX<https://aka.ms/edx-devops200_9x-about>)

**Comment by carolynvs** [comment]
This is working for me with the latest release (0.1.4). Thank you! ✨
