### ISSUE TITLE
Use ReadCloser for body instead of ReadSeeker

### ISSUE THREAD

**Issue by michaelbironneau** [Azure/azure-storage-blob-go#44]
We would like to store a file that a user uploads to blob storage. The `Body` field of the `http.Request` struct where we will access the uploaded file is an `io.ReadCloser`, whereas the blob storage method `PutBlob` requires an `io.ReadSeeker`. Can you please downgrade the requirement to `io.ReadCloser` or explain how to work around this? Third party blob storage libraries do not have the same limitation because they do not implement as robust retry policies, so perhaps there is an alternative implementation you could make that takes a `ReadCloser` but does not seek back to a successful offset to retry from on failure. Thanks

**Comment by JeffreyRichter** [comment]
We make use of it in the retry policy. I did a pretty large write up of why these decisions where made. I have also added an UploadSteamToBlockBlob method that basically reads from an io.ReadCloser into 1+buffers (configurable) and then writes them with full resiliency via retry support. You'll want to move to the 2017 azblob package.

-- Jeffrey Richter (watch Architecting Distributed Cloud Apps<https://aka.ms/RichterCloudApps> on YouTube<https://aka.ms/RichterCloudApps> or edX<https://aka.ms/edx-devops200_9x-about>)
________________________________

**Comment by JeffreyRichter** [comment]
Yes, you are correct. Ze (cc'd) will hopefully be uploading code today that has the UploadStreamToBlockBlob method in it.

-- Jeffrey Richter (watch Architecting Distributed Cloud Apps<https://aka.ms/RichterCloudApps> on YouTube<https://aka.ms/RichterCloudApps> or edX<https://aka.ms/edx-devops200_9x-about>)
________________________________

**Comment by JeffreyRichter** [comment]
The new code is available. the function to read from a stream and upload its data to a block blob can be found [here](https://github.com/Azure/azure-storage-blob-go/blob/master/2017-07-29/azblob/highlevel.go#L372).

**Comment by michaelbironneau** [comment]
Thanks @JeffreyRichter .
