### ISSUE TITLE
UploadStreamToBlockBlob does not return error correctly

### ISSUE THREAD

**Issue by sandeepkru** [Azure/azure-storage-blob-go#52]
`UploadStreamToBlockBlob` which calls `uploadStream` is not returning error correctly to user. If reader is wrapped up with error, we were expecting this call to fail the transfer, instead currently below code simply copies stream to buffer irrespective of error type.

https://github.com/Azure/azure-storage-blob-go/blob/f0a732ea9441c73511367d5861da6bda664ffabd/2017-07-29/azblob/highlevel.go#L492

Once we break out of upload process here https://github.com/Azure/azure-storage-blob-go/blob/eaae161d9d5e07363f04ddb19d84d57efc66d1a1/2018-03-28/azblob/highlevel.go#L501
it simply masks occurred error and returns success to caller
https://github.com/Azure/azure-storage-blob-go/blob/eaae161d9d5e07363f04ddb19d84d57efc66d1a1/2018-03-28/azblob/highlevel.go#L509

I believe correct behavior here should fail the transfer and return error to user, this used be to be the behavior in older SDK [azure-sdk-for-go CreateBlockBlobFromReader](https://github.com/Azure/azure-sdk-for-go/blob/51228ee60b238eaa5a9d53adc82ebd8b321bca4f/storage/blockblob.go#L125)

Please let me know if you need any more details on this.

**Comment by ncw** [comment]
Any news on this issue?  Can we send a PR?

**Comment by zezha-msft** [comment]
Hi @ncw, sorry we haven't gotten to this item yet.

Yes! We'd love to receive a PR if you are willing to contribute! 👍

**Comment by ncw** [comment]
I have sent a PR #67 for your delight and entertainment ;-)

**Comment by zezha-msft** [comment]
This was fixed in [version 0.2.0](https://github.com/Azure/azure-storage-blob-go/releases/tag/0.2.0).

**Comment by ncw** [comment]
thank you :-)
