### ISSUE TITLE
Add Blob-Specific Request Headers when committing block list

### ISSUE THREAD

**Issue by someone1** [Azure/azure-storage-blob-go#57]
Right now, there is no way to set the `x-ms-blob-content-md5` header when committing a block list, only  the MD5 header for the request body is available.

See: https://docs.microsoft.com/en-us/rest/api/storageservices/put-block-list

**Comment by JeffreyRichter** [comment]
When you call CommitBlockList, you can pass it a BlobHTTPHeaders object which includes an MD5 value. This value is sent using the x-ms-blob-content-md5 header. There is currently no way to set the Content-MD5 header because we do not think that this is very useful.

**Comment by someone1** [comment]
Ahhh - agreed, I (incorrectly) assumed it wasn't being done that way! Thank you!
