### ISSUE TITLE
GetBlobProperties error doesn't populate service code correctly in case of `404`

### ISSUE THREAD

**Issue by sandeepkru** [Azure/azure-storage-blob-go#58]
### Which version of the SDK was used?
- Using latest - `2018-03-28/azblob`
### Which platform are you using? (ex: Windows, Linux, Debian)
- Mac OS X
### What problem was encountered?
GetBlobProperties error code doesn't populate service code correctly when casted to `storageError` if blob doesn't exist
### How can we reproduce the problem in the simplest way?
```console
 _, err := blobProperties, err = blob.GetProperties(ctx, options)
if storageErr, ok := err.(azblob.StorageError); ok && (storageErr.ServiceCode() == azblob.ServiceCodeContainerNotFound)  {
 <=== This doesn't work but if  change this as below it works
}

if storageErr, ok := err.(azblob.StorageError); ok && (storageErr.ServiceCode() == azblob.ServiceCodeContainerNotFound || storageErr.Response().StatusCode == http.StatusNotFound) {
===> This works by checking explicitly Response status code, 
}
```
### Have you found a mitigation/solution?
I didn't investigate further, since I wasn't sure if it bug or expected behavior.

**Comment by zezha-msft** [comment]
This was fixed in [version 0.2.0](https://github.com/Azure/azure-storage-blob-go/releases/tag/0.2.0).
