### ISSUE TITLE
Unexpected context deadline exceeded

### ISSUE THREAD

**Issue by jeffw-wherethebitsroam** [Azure/azure-storage-blob-go#60]
### Which version of the SDK was used?

master 197d1c0aea1b9eedbbaee0a1a32bf81e879bde80
(go get github.com/Azure/azure-storage-blob-go/2018-03-28/azblob)

### Which platform are you using? (ex: Windows, Linux, Debian)

macOS

### What problem was encountered?

Trying a simple example to download a file. I passed in context.Background() but got the error:
context deadline exceeded

### How can we reproduce the problem in the simplest way?

Code below, credentials and blob information changed, but otherwise unchanged. I guess the blob must be big enough to trigger the deadline. In my case it was 723.75 MiB.

```golang
	credential := azblob.NewSharedKeyCredential("account", "key")
	p := azblob.NewPipeline(credential, azblob.PipelineOptions{})

	u, _ := url.Parse("https://account.blob.core.windows.net/")

	serviceURL := azblob.NewServiceURL(*u, p)
	containerURL := serviceURL.NewContainerURL("container")
	blobURL := containerURL.NewBlobURL("blob")

	log.Printf("starting")

	ctx := context.Background()
	blob, err := blobURL.Download(ctx, 0, 0, azblob.BlobAccessConditions{}, false)
	if err != nil {
		log.Fatal(err)
	}

	body := blob.Body(azblob.RetryReaderOptions{})
	defer body.Close()

	f, err := os.Create("output")
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	_, err = io.Copy(f, body)
	if err != nil {
		log.Fatal(err)
	}
```

Output:

```
2018/08/08 15:18:52 starting
2018/08/08 15:19:52 context deadline exceeded
```

### Have you found a mitigation/solution?

Not as yet.

**Comment by jeffw-wherethebitsroam** [comment]
Ok, looks like I found the solution, I need to extend the TryTimeout on the Pipeline:

```golang
	p := azblob.NewPipeline(credential, azblob.PipelineOptions{
		Retry: azblob.RetryOptions{
			TryTimeout: 5 * time.Minute,
		},
	})
```
This seems to work, but is a little unexpected. I'm not sure if this could be made more obvious in the docs or error message?

**Comment by JeffreyRichter** [comment]
The pipeline includes a retry policy which places a per-try timeout on each request. I suspect that you are downloading a large file, perhaps over a slow network, that is causing the timeout.

Try adjusting the per-try timeout via the PipelineOptions. An example is shown here: https://godoc.org/github.com/Azure/azure-storage-blob-go/2018-03-28/azblob#example-NewPipeline





-- Jeffrey Richter (watch Architecting Distributed Cloud Apps<https://aka.ms/RichterCloudApps> on YouTube<https://aka.ms/RichterCloudApps> or edX<https://aka.ms/edx-devops200_9x-about>)
________________________________

**Comment by JeffreyRichter** [comment]
Hi Jeff,

I'm curious, how did you figure this out on your own?
What led you to the solution?

-- Jeffrey Richter (watch Architecting Distributed Cloud Apps<https://aka.ms/RichterCloudApps> on YouTube<https://aka.ms/RichterCloudApps> or edX<https://aka.ms/edx-devops200_9x-about>)
________________________________

**Comment by jatoben** [comment]
@JeffreyRichter In case it's helpful, I ran into this today too; I was uploading a large blob, rather than downloading, and my connection was fairly fast.

I re-read the docs to find the answer; I guess at first, I hadn't realized that the timeout was a maximum bound for the entire upload operation, even if steady progress was still being made. I found this comment to be the most useful:

https://github.com/Azure/azure-storage-blob-go/blob/463a4570c8e8e8169f78de28fa8bf06eabcb78a3/2018-03-28/azblob/zc_policy_retry.go#L37-L42

**Comment by JeffreyRichter** [comment]
I appreciate your post. If love to make this more obvious but I don't know the best course of action to take. One idea I had was to return my own error with helpful text but then it won't be a deadline exceeded error which is what go programmers would expect. Error handling in go is problematic. There are some our handling proposals for go 2 which would allow me to wrap the deadline exceeded error in my own, richer error but this would be some time in the future and if like to do something sooner. 

Any suggestions?

**Comment by jeffw-wherethebitsroam** [comment]
@JeffreyRichter I missed your question - I actually had to go look at the code to figure it out.

It looks like you might be able to track whether the user's context timeout or the RetryOptions TryTimeout is used in the RetryOptions pipeline.FactoryFunc. Then respond with a specific error. But I see what you mean: at the moment you are returning a context.DeadlineExceeded error, and this would be lost.

For me at least, I would only expect to receive a context.DeadlineExceeded error if the deadline was exceeded for the context I passed in (that was what confused me in the first place). If there was some separate, well defined error for when the the RetryOptions.TryTimeout was exceeded, that would be fine for me, but I guess it might cause problems for existing clients.

**Comment by JeffreyRichter** [comment]
This library is the best one available for Go today. Now, with the new error support in Go, we can improve the experience here. When the inner (per-try) context expires, the library can add a message to the error with helpful guidance directing you to the RetryOptions TryTimeout field letting you know what happened and how to address it. 

We don't want to get rid of the per-try timeout entirely because, if a service doesn't respond, then your goroutine is just hung. 

And, Go's context fully support composing contexts and we take advantage of this to make this work. In a future version of this library, we'll add the richer error support to simplify diagnosability.

**Comment by yakuter** [comment]
> Ok, looks like I found the solution, I need to extend the TryTimeout on the Pipeline:
> 
> ```go
> 	p := azblob.NewPipeline(credential, azblob.PipelineOptions{
> 		Retry: azblob.RetryOptions{
> 			TryTimeout: 5 * time.Minute,
> 		},
> 	})
> ```
> 
> This seems to work, but is a little unexpected. I'm not sure if this could be made more obvious in the docs or error message?

This saved my life 👍  Thank you very much.
