### ISSUE TITLE
OpenBSD and NetBSD build issue

### ISSUE THREAD

**Issue by kpfaulkner** [Azure/azure-storage-blob-go#72]
Hi

I'm cross compiling one of my apps that I've just ported to this new SDK (from azure-sdk-for-go). I'm using gox to trigger a bunch of cross platform builds.

Most platforms are fine, but OpenBSD and NetBSD fail.

gox -ldflags "-X main.Version=0.4.0"
Number of parallel builds: 3

-->      darwin/386: azurecopy/azurecopycommand
-->    darwin/amd64: azurecopy/azurecopycommand
-->     linux/amd64: azurecopy/azurecopycommand
-->       linux/arm: azurecopy/azurecopycommand
-->       linux/386: azurecopy/azurecopycommand
-->     freebsd/386: azurecopy/azurecopycommand
-->   freebsd/amd64: azurecopy/azurecopycommand
-->     openbsd/386: azurecopy/azurecopycommand
-->   openbsd/amd64: azurecopy/azurecopycommand
-->     windows/386: azurecopy/azurecopycommand
-->   windows/amd64: azurecopy/azurecopycommand
-->     freebsd/arm: azurecopy/azurecopycommand
-->      netbsd/386: azurecopy/azurecopycommand
-->    netbsd/amd64: azurecopy/azurecopycommand
-->      netbsd/arm: azurecopy/azurecopycommand

5 errors occurred:
--> openbsd/386 error: exit status 2
Stderr: # github.com/azure/azure-storage-blob-go/2016-05-31/azblob
..\..\github.com\azure\azure-storage-blob-go\2016-05-31\azblob\highlevel.go:165:7: undefined: mmf
..\..\github.com\azure\azure-storage-blob-go\2016-05-31\azblob\highlevel.go:167:12: undefined: newMMF

--> openbsd/amd64 error: exit status 2
Stderr: # github.com/azure/azure-storage-blob-go/2016-05-31/azblob
..\..\github.com\azure\azure-storage-blob-go\2016-05-31\azblob\highlevel.go:165:7: undefined: mmf
..\..\github.com\azure\azure-storage-blob-go\2016-05-31\azblob\highlevel.go:167:12: undefined: newMMF

--> netbsd/386 error: exit status 2
Stderr: # github.com/azure/azure-storage-blob-go/2016-05-31/azblob
..\..\github.com\azure\azure-storage-blob-go\2016-05-31\azblob\highlevel.go:165:7: undefined: mmf
..\..\github.com\azure\azure-storage-blob-go\2016-05-31\azblob\highlevel.go:167:12: undefined: newMMF

--> netbsd/amd64 error: exit status 2
Stderr: # github.com/azure/azure-storage-blob-go/2016-05-31/azblob
..\..\github.com\azure\azure-storage-blob-go\2016-05-31\azblob\highlevel.go:165:7: undefined: mmf
..\..\github.com\azure\azure-storage-blob-go\2016-05-31\azblob\highlevel.go:167:12: undefined: newMMF

--> netbsd/arm error: exit status 2
Stderr: # github.com/azure/azure-storage-blob-go/2016-05-31/azblob
..\..\github.com\azure\azure-storage-blob-go\2016-05-31\azblob\highlevel.go:165:7: undefined: mmf
..\..\github.com\azure\azure-storage-blob-go\2016-05-31\azblob\highlevel.go:167:12: undefined: newMMF

I don't have a minimum reproducible setup yet, but wanted to check if this "highlevel/mmf" error was already known. If not, I'll try and make a minimum repro step.

When using the azure-sdk-for-go, OpenBSD and NetBSD built fine.

Thanks

Ken

**Comment by zezha-msft** [comment]
Hi @kpfaulkner, thanks for reaching out!

I was able to reproduce your problem: we missed `openbsd` and `netbsd` on this [line](https://github.com/Azure/azure-storage-blob-go/blob/master/2018-03-28/azblob/zc_mmf_unix.go#L1). I'll provide a fix as soon as possible.

If you don't mind, I would strongly recommend to use the 2018-03-28 version instead of the 2016-05-31 version. Thanks!

**Comment by kpfaulkner** [comment]
Hi,

I initially was using 2018-03-28 but hit an issue with it (sorry, honestly cannot remember the error I got), but 2016-05-31 worked a charm so left it will that. I'll try and go back and see what my error was with the newer version.

Thanks

Ken

**Comment by zezha-msft** [comment]
Hi @kpfaulkner, that'd be great! Please let us know what the problem is and we'll try to fix it right away.
