### ISSUE TITLE
PutBlock failed due to missing content length parameter

### ISSUE THREAD

**Issue by ToruMakabe** [Azure/azure-storage-blob-go#8]
I got an error "Content-Length HTTP header is missing" when I did PutBlock in UploadStreamToBlockBlob.

https://github.com/Azure/azure-storage-blob-go/blob/master/2016-05-31/azblob/highlevel.go#L49

```
		if blockNum == numBlocks-1 { // Last block
			blockSize = streamSize % o.BlockSize
		}
```

I suspect that Content-Length of last block should be 0 when streamSize can be divided evenly by o.BlockSize. So, PubBlock failed.

Could you check it?

**Comment by JeffreyRichter** [comment]
Yes, you are correct. I modified the code to:
```
if blockNum == numBlocks-1 { // Last block
   blockSize = streamSize - (blockNum * o.BlockSize) // Remove size of all uploaded blocks from total
}
```
Fixed with pull request: https://github.com/Azure/azure-storage-blob-go/commit/0bcf4855f315965d6b3ad46ed4091d31bc95db25

**Comment by ToruMakabe** [comment]
Thanks!
