### ISSUE TITLE
Remove unavailable versions from the README.md

### ISSUE THREAD

**Issue by elsesiy** [Azure/azure-storage-blob-go#85]
### Which version of the SDK was used?
I was using the [2016-05-31](github.com/Azure/azure-storage-blob-go/2016-05-31/azblob) version which has been removed with the latest release. Unfortunately this broke not only my project build but also dependent projects like azure-eventhubs-go for which I filed an [issue](https://github.com/Azure/azure-event-hubs-go/issues/68) already. I don't think it's good practice to delete tags but I'm sure you'll have your reasons to do so. At least please make it clear in the README by removing the version section altogether as the references to old versions are worth nothing.
### Which platform are you using? (ex: Windows, Linux, Debian)
Mac OS X 10.13.6
### What problem was encountered?
README still references versions of the repo that have been removed with the latest release
### How can we reproduce the problem in the simplest way?
Follow these two links mentioned in the README
github.com/Azure/azure-storage-blob-go/2016-05-31/azblob
github.com/Azure/azure-storage-blob-go/2017-07-29/azblob
### Have you found a mitigation/solution?
N/A

**Comment by zezha-msft** [comment]
Hi @elsesiy, thanks for reaching out!

I apologize for the inconvenience, but to clarify, we **DID NOT** delete any tag on Github. What tag are you referring to exactly?

The [version table](https://github.com/Azure/azure-storage-blob-go#version-table) was added to clarify that the 2016 and 2017 service versions are still available, in the [0.2.0 version](https://github.com/Azure/azure-storage-blob-go/releases/tag/0.2.0) of the SDK. The users of the SDK can still access them by pinning the version using `dep`. In general, we would strongly advise not to rely on the master branch, which could change frequently as we are actively working on this SDK.

**Comment by elsesiy** [comment]
@zezha-msft Sorry, you're right. I had some issues with using dep in combination with go modules that's why I was using master in which the two versions have been removed. I'll get it up and running tomorrow I guess..

**Comment by zezha-msft** [comment]
@elsesiy sounds good! Please let us know if you encounter any problem.
